from __future__ import annotations
#

"""QC flag audit pipeline.

Extracted from: D:/OneDrive/PAPER_GRADIENT_TOWER/PYTHON_PIPELINE/AUDIT_FLAGS_GRADIENT_TOWER_OPTIMIZED_AUDITED.ipynb
Generated by Codex on 2026-05-25.
"""


# %% Original notebook cell 1


import os
import re
import warnings
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, Iterable, List, Literal, Optional, Tuple
from pathlib import Path
from datetime import datetime, timezone

import numpy as np
import pandas as pd
import xarray as xr

import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib.colors import BoundaryNorm
from matplotlib.ticker import FormatStrFormatter, PercentFormatter

import plotly.graph_objects as go
from plotly.subplots import make_subplots
from typing import Optional

warnings.filterwarnings("default")


# %% Original notebook cell 2

# =============================================================================
# Configuration for the OGHYO Gradient Tower Dataset, including physical constants, 
# QC bitmasks, and a dataclass for tower configuration with validation logic.
# OGHYO Gradient Tower Dataset
# =============================================================================

# -----------------------------
# 0) Physical Constants and QC Flags
# -----------------------------
KAPPA = 0.4
G = 9.80665
RD = 287.05
RV = 461.5
CP = 1004.67
P0 = 101325.0
T0_STD = 288.15
LAPSE = 0.0065

# Bitmasks for quality control (QC)
BIT_MISSING = 1 << 0    # 1
BIT_RANGE = 1 << 1      # 2
BIT_STEP = 1 << 2       # 4
BIT_PERSIST = 1 << 3    # 8
BIT_SPIKE = 1 << 4      # 16
BIT_CALM = 1 << 5       # 32
BIT_INCONSIST = 1 << 6  # 64
BIT_RESAMPLE = 1 << 7   # 128

# -----------------------------
# 4) Tower Configuration
# -----------------------------
@dataclass
class TowerConfig:
    # Physical heights of the tower
    heights_m: List[float] = field(default_factory=lambda: [2.0, 6.0, 12.0, 24.0])

    # Column mapping by sensor and height
    temp_cols: Dict[float, str] = field(default_factory=lambda: {
        2.0: "temp_n1", 6.0: "temp_n2", 12.0: "temp_n3", 24.0: "temp_n5"
    })
    rh_cols: Dict[float, str] = field(default_factory=lambda: {
        2.0: "RH_n1", 6.0: "RH_n2", 12.0: "RH_n3", 24.0: "RH_n5"
    })
    wind_cols: Dict[float, str] = field(default_factory=lambda: {
        2.0: "wind_n1", 6.0: "wind_n2", 12.0: "wind_n3", 24.0: "wind_n5"
    })
    wdir_cols: Dict[float, str] = field(default_factory=lambda: {
        24.0: "dir_wind"
    })

    # Geographical and temporal parameters
    site_altitude_m: float = 3315.0
    timezone: str = "America/Lima"
    naive_are_local: bool = True
    duplicate_policy: str = "first"
    sample_period_s: Optional[int] = None
    target_freq: Optional[str] = None

    # Plausible meteorological ranges (Range Flags)
    ranges: Dict[str, Tuple[float, float]] = field(default_factory=lambda: {
        "temp": (-20.0, 40.0),
        "rh": (0.0, 100.0),
        "wind": (0.0, 50.0),
        "wdir": (0.0, 360.0),
    })

    # Maximum allowed change limits between consecutive records (Step / Saltos)
    step_limits: Dict[str, float] = field(default_factory=lambda: {
        "temp": 1.5,
        "rh": 8.0,
        "wind": 10.0,
        "wdir": 120.0,
    })

    # Tolerance for frozen sensor detection (Persistence)
    persistence_eps: Dict[str, float] = field(default_factory=lambda: {
        "temp": 0.1,
        "rh": 0.2,
        "wind": 0.05,
        "wdir": 2.0,
    })
    persistence_min_samples: int = 20

    # Iterative filter by Median Absolute Deviation (Spikes / Picos)
    mad_window: int = 21
    mad_k_by_var: Dict[str, float] = field(default_factory=lambda: {
        "temp": 5.0,
        "rh": 6.0,
        "wind": 10.0,
        "wdir": 10.0,
    })

    # Threshold speed for anemometric calm
    calm_ws_ms: float = 0.2

    # Hard discard policy in the pipeline per bit of error
    hard_fail_bits: Tuple[int, ...] = (BIT_RANGE, BIT_STEP, BIT_SPIKE)

    # Optional routes for data export
    save_clean_csv: Optional[str] = None
    save_flags_csv: Optional[str] = None
    save_summary_csv: Optional[str] = None
    save_clean_parquet: Optional[str] = None
    save_flags_parquet: Optional[str] = None
    save_summary_parquet: Optional[str] = None

    def __post_init__(self) -> None:
        """Logical validator of physical and mathematical integrity of the configuration."""
        if not self.heights_m:
            raise ValueError("heights_m cannot be empty")
        if len(set(self.heights_m)) != len(self.heights_m):
            raise ValueError("heights_m contains duplicate heights.")
        if self.site_altitude_m < 0:
            raise ValueError("site_altitude_m cannot be a negative value.")
        if self.mad_window < 3:
            raise ValueError("mad_window must be greater than or equal to 3.")
        if self.mad_window % 2 == 0:
            raise ValueError("mad_window must be an odd number for centered windows.")
        if self.persistence_min_samples < 2:
            raise ValueError("persistence_min_samples must be >= 2.")
        if self.calm_ws_ms < 0:
            raise ValueError("calm_ws_ms must be a non-negative value.")
        if self.duplicate_policy not in {"first", "last", "mean", "median"}:
            raise ValueError("duplicate_policy must be one of the following: first, last, mean, median.")

        # Verificar existencia de variables críticas
        required_vtypes = ("temp", "rh", "wind", "wdir")
        for v in required_vtypes:
            if v not in self.ranges:
                raise ValueError(f"The 'ranges' definition for the variable is missing. '{v}'.")
            if v not in self.step_limits:
                raise ValueError(f"The 'step_limits' definition for the variable is missing. '{v}'.")
            if v not in self.persistence_eps:
                raise ValueError(f"The 'persistence_eps' definition for the variable is missing. '{v}'.")
            if v not in self.mad_k_by_var:
                raise ValueError(f"The 'mad_k_by_var' definition for the variable is missing. '{v}'.")

        # Verify mathematical consistency of lower and upper limits
        for v, (lo, hi) in self.ranges.items():
            if lo > hi:
                raise ValueError(f"Invalid range for '{v}': the lower limit cannot be greater than the upper limit.")

        for v, k in self.mad_k_by_var.items():
            if k <= 0:
                raise ValueError(f"mad_k_by_var['{v}'] must be a strictly positive multiplier.")

        # Verify that the mapped sensors correspond to existing physical heights in the structure
        all_mappings = {
            "temp_cols": self.temp_cols,
            "rh_cols": self.rh_cols,
            "wind_cols": self.wind_cols,
            "wdir_cols": self.wdir_cols,
        }
        heights_set = set(self.heights_m)
        for name, mapping in all_mappings.items():
            for z in mapping.keys():
                if z not in heights_set:
                    raise ValueError(f"La altura {z} declarada en '{name}' no existe dentro de 'heights_m'.")


def make_default_tower_config() -> TowerConfig:
    """Returns the default audited configuration for the OGHYO project."""
    return TowerConfig()


def validate_tower_config_integrity(cfg: TowerConfig) -> pd.DataFrame:
    """Returns a detailed report in Pandas evaluating global collisions of column names.

    Modified to detect if the same column name was erroneously assigned to different variables.
    """
    rows = []
    mappings = {
        "temp_cols": cfg.temp_cols,
        "rh_cols": cfg.rh_cols,
        "wind_cols": cfg.wind_cols,
        "wdir_cols": cfg.wdir_cols,
    }
    
    # Global list to track if a physical column is assigned to two different sensors simultaneously
    all_assigned_cols = []
    for mapping in mappings.values():
        all_assigned_cols.extend(list(mapping.values()))

    for name, mapping in mappings.items():
        cols = list(mapping.values())
        
        # 1. Internal duplicates within the same dictionary
        internal_dups = sorted({c for c in cols if cols.count(c) > 1})
        
        # 2. Cross-variable collisions in the tower
        cross_collisions = sorted({c for c in cols if all_assigned_cols.count(c) > cols.count(c)})
        
        # Status of the analyzed row
        has_issues = bool(internal_dups or cross_collisions)
        
        rows.append({
            "mapping": name,
            "n_columns": len(cols),
            "duplicated_internal_names": ", ".join(internal_dups) if internal_dups else "Ninguno",
            "cross_variable_collisions": ", ".join(cross_collisions) if cross_collisions else "Ninguna",
            "status": "REVIEW" if has_issues else "OK",
        })
        
    return pd.DataFrame(rows)


# Secure initialization of the script's global configuration
cfg = make_default_tower_config()


# %% Original notebook cell 3

# ==================================================================================
# CONSISTENT DATAFRAME READER FROM NETCDF - OPTIMIZED & FIXED VERSION
# OGHYO Gradient Tower Dataset
# ===============================================================================

# --- Global tower configuration ---
HEIGHTS_M = [2.0, 6.0, 12.0, 24.0]

TEMP_COLS = {2.0: "temp_n1", 6.0: "temp_n2", 12.0: "temp_n3", 24.0: "temp_n5"}
RH_COLS = {2.0: "RH_n1", 6.0: "RH_n2", 12.0: "RH_n3", 24.0: "RH_n5"}
WIND_COLS = {2.0: "wind_n1", 6.0: "wind_n2", 12.0: "wind_n3", 24.0: "wind_n5"}
WDIR_COLS = {24.0: "dir_wind"}

# Standard Quality Control Bit Convention
BIT_MISSING = 1


def convert_index_utc_to_local(
    df: Optional[pd.DataFrame],
    local_tz: str = "America/Lima",
    remove_timezone: bool = True,
) -> Optional[pd.DataFrame]:
    """Convert a DataFrame DatetimeIndex from UTC to a local timezone."""
    if df is None or df.empty:
        return df

    out = df.copy()
    out.index = pd.to_datetime(out.index)

    if out.index.tz is None:
        out.index = out.index.tz_localize("UTC")
    else:
        out.index = out.index.tz_convert("UTC")

    out.index = out.index.tz_convert(local_tz)

    if remove_timezone:
        out.index = out.index.tz_localize(None)

    out.index.name = "time"
    return out


def convert_index_utc_to_lima(df: Optional[pd.DataFrame], remove_timezone: bool = True) -> Optional[pd.DataFrame]:
    """Backward-compatible alias for the original function name."""
    return convert_index_utc_to_local(df, local_tz="America/Lima", remove_timezone=remove_timezone)


def extract_2d_variable_to_original_columns(
    ds: xr.Dataset,
    var_name: str,
    col_map: Dict[float, str],
) -> pd.DataFrame:
    """Extract a 2-D variable with dimensions (time, height) into original tower columns.

    Optimized to bypass redundant pandas transformations inside loops using direct NumPy arrays.
    """
    time_index = pd.to_datetime(ds["time"].values)

    if var_name not in ds:
        return pd.DataFrame(index=time_index)

    da = ds[var_name]

    if not {"time", "height"}.issubset(set(da.dims)):
        raise ValueError(f"Variable {var_name!r} must have dimensions ('time', 'height'). Found: {da.dims}")

    if "height" not in da.coords:
        raise ValueError(f"Variable {var_name!r} has a height dimension but no height coordinate.")

    out = pd.DataFrame(index=time_index)
    available_heights = np.asarray(da["height"].values, dtype=float)

    for height, original_col in col_map.items():
        if np.any(np.isclose(available_heights, height)):
            # Find the closest numerical index
            idx = np.argmin(np.abs(available_heights - height))
            # Optimization: Direct extraction using slicing of native vectors (.values)
            out[original_col] = da.isel(height=idx).values

    out.index.name = "time"
    return out


def extract_derived_variables(ds: xr.Dataset, var_name: str) -> pd.DataFrame:
    """Extract derived time-height variables such as q and theta_v directly to NumPy."""
    time_index = pd.to_datetime(ds["time"].values)

    if var_name not in ds:
        return pd.DataFrame(index=time_index)

    da = ds[var_name]

    if not {"time", "height"}.issubset(set(da.dims)):
        raise ValueError(f"Variable {var_name!r} must have dimensions ('time', 'height'). Found: {da.dims}")

    out = pd.DataFrame(index=time_index)

    for idx, height in enumerate(np.asarray(da["height"].values, dtype=float)):
        suffix = str(int(height)) if float(height).is_integer() else str(height).replace(".", "p")
        # Optimization: Direct access using native position index without Pandas overhead
        out[f"{var_name}_{suffix}"] = da.isel(height=idx).values

    out.index.name = "time"
    return out


def extract_qc_flags_to_original_columns(
    ds: xr.Dataset,
    qc_var_name: str,
    col_map: Dict[float, str],
    fill_missing_flag: int = BIT_MISSING,
) -> pd.DataFrame:
    """Extract QC flags with original tower column names, avoiding global dict lookups."""
    df = extract_2d_variable_to_original_columns(ds, qc_var_name, col_map)

    for col in df.columns:
# Empty or NaN flags are forced to the corresponding missing (MISSING) bitmask
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(fill_missing_flag).astype("int32")

    return df


def _concat_or_empty(parts: List[pd.DataFrame], index: pd.DatetimeIndex) -> pd.DataFrame:
    valid = [df for df in parts if df is not None and not df.empty]
    if valid:
        return pd.concat(valid, axis=1)
    return pd.DataFrame(index=index)


def read_saved_tower_dataframes_from_netcdf(
    nc_file: str,
    convert_to_local: Optional[bool] = None,
    local_tz: str = "America/Lima",
    remove_timezone: bool = True,
    engine: str = "netcdf4",
    **legacy_kwargs: Any,
) -> Tuple[pd.DataFrame, pd.DataFrame, Optional[pd.DataFrame], xr.Dataset, Optional[xr.Dataset]]:
    """Read cleaned, QC flags and raw-uncontrolled DataFrames from the OGHYO tower NetCDF file."""
    if convert_to_local is None:
        convert_to_local = bool(legacy_kwargs.pop("convert_to_lima", True))
    elif "convert_to_lima" in legacy_kwargs:
        warnings.warn("Both convert_to_local and convert_to_lima were supplied; using convert_to_local.")
        legacy_kwargs.pop("convert_to_lima")

    if legacy_kwargs:
        raise TypeError(f"Unexpected keyword argument(s): {list(legacy_kwargs)}")

    if not os.path.exists(nc_file):
        raise FileNotFoundError(f"NetCDF file does not exist: {os.path.abspath(nc_file)}")

    # 1. Carga de dataset principal de variables procesadas
    ds = xr.open_dataset(nc_file, engine=engine, decode_times=True)
    time_index = pd.to_datetime(ds["time"].values)

    # 2. Carga segura del grupo "raw_uncontrolled"
    try:
        ds_raw = xr.open_dataset(nc_file, group="raw_uncontrolled", engine=engine, decode_times=True)
    except Exception as exc:
        warnings.warn(f"Could not open NetCDF group 'raw_uncontrolled': {exc}")
        ds_raw = None

    # 3. Procesamiento y reconstrucción de variables limpias y derivadas
    cleaned_parts = [
        extract_2d_variable_to_original_columns(ds, "ta", TEMP_COLS),
        extract_2d_variable_to_original_columns(ds, "hur", RH_COLS),
        extract_2d_variable_to_original_columns(ds, "ws", WIND_COLS),
        extract_2d_variable_to_original_columns(ds, "wd", WDIR_COLS),
        extract_derived_variables(ds, "q"),
        extract_derived_variables(ds, "theta_v"),
    ]
    cleaned_from_nc = _concat_or_empty(cleaned_parts, index=time_index)

    if "P_Pa" in ds:
        # Optimización: Extracción directa sin instanciar dataframe intermedio de Pandas
        cleaned_from_nc["P_Pa"] = ds["P_Pa"].values

    # 4. Procesamiento de banderas de control de calidad
    flag_parts = [
        extract_qc_flags_to_original_columns(ds, "ta_qc_flags", TEMP_COLS),
        extract_qc_flags_to_original_columns(ds, "hur_qc_flags", RH_COLS),
        extract_qc_flags_to_original_columns(ds, "ws_qc_flags", WIND_COLS),
        extract_qc_flags_to_original_columns(ds, "wd_qc_flags", WDIR_COLS),
    ]
    flags_from_nc = _concat_or_empty(flag_parts, index=time_index)

    # 5. Tratamiento consistente del grupo crudo (Desarticulación limpia de MultiIndex de alturas)
    if ds_raw is not None:
        if "height" in ds_raw.dims:
            # Si tiene altura como dimensión, se unifica de manera idéntica al dataset limpio
            raw_parts = [
                extract_2d_variable_to_original_columns(ds_raw, "ta", TEMP_COLS),
                extract_2d_variable_to_original_columns(ds_raw, "hur", RH_COLS),
                extract_2d_variable_to_original_columns(ds_raw, "ws", WIND_COLS),
                extract_2d_variable_to_original_columns(ds_raw, "wd", WDIR_COLS),
            ]
            raw_from_nc = _concat_or_empty(raw_parts, index=time_index)
        else:
            # Si es un dataset plano unidimensional (sólo tiempo)
            raw_from_nc = ds_raw.to_dataframe().dropna(axis=1, how="all")
            if isinstance(raw_from_nc.index, pd.MultiIndex):
                if "time" not in raw_from_nc.index.names:
                    raise ValueError("raw_uncontrolled group has a MultiIndex without a 'time' level.")
                raw_from_nc = raw_from_nc.reset_index().set_index("time")
            raw_from_nc.index = pd.to_datetime(raw_from_nc.index)
            raw_from_nc.index.name = "time"
    else:
        raw_from_nc = None

    # 6. Conversión horaria centralizada y segura
    if convert_to_local:
        cleaned_from_nc = convert_index_utc_to_local(cleaned_from_nc, local_tz=local_tz, remove_timezone=remove_timezone)
        flags_from_nc = convert_index_utc_to_local(flags_from_nc, local_tz=local_tz, remove_timezone=remove_timezone)
        if raw_from_nc is not None:
            raw_from_nc = convert_index_utc_to_local(raw_from_nc, local_tz=local_tz, remove_timezone=remove_timezone)

    return cleaned_from_nc, flags_from_nc, raw_from_nc, ds, ds_raw


def inspect_reconstructed_dataframes(
    cleaned_from_nc: pd.DataFrame,
    flags_from_nc: pd.DataFrame,
    raw_from_nc: Optional[pd.DataFrame] = None,
) -> None:
    """Print a compact integrity inspection for reconstructed DataFrames."""
    for name, df in [("cleaned_from_nc", cleaned_from_nc), ("flags_from_nc", flags_from_nc), ("raw_from_nc", raw_from_nc)]:
        print(f"\n=== {name} ===")
        if df is None:
            print("Not available")
            continue
        print("shape:", df.shape)
        print("index tz:", getattr(df.index, "tz", None))
        print("duplicated times:", int(df.index.duplicated().sum()))
        if len(df.index) > 0:
            print("time range:", df.index.min(), "to", df.index.max())
        print("columns:", list(df.columns))


# %% Original notebook cell 4

# =============================================================================
# MÓDULO DE DIAGNÓSTICO FORENSE Y VISUALIZACIÓN INTERACTIVA DE QC
# OGHYO Gradient Tower Dataset
# =============================================================================
# --- Asegurar compatibilidad con las máscaras de bits del módulo de configuración ---
BIT_MISSING = 1 << 0      # 1
BIT_RANGE = 1 << 1        # 2
BIT_STEP = 1 << 2         # 4
BIT_PERSIST = 1 << 3      # 8
BIT_SPIKE = 1 << 4        # 16
BIT_CALM = 1 << 5         # 32
BIT_INCONSIST = 1 << 6    # 64
BIT_RESAMPLE = 1 << 7     # 128


def get_flag_names(
    bitmask: float, 
    severity: float = 0.0, 
    k_critic: Optional[float] = None, 
    nan_as_missing: bool = False
) -> str:
    """Converts QC bitmask values into readable diagnostic labels."""
    flags_map = {
        BIT_MISSING: "MISSING",
        BIT_RANGE: "RANGE",
        BIT_STEP: "STEP",
        BIT_PERSIST: "PERSIST",
        BIT_SPIKE: "SPIKE",
        BIT_CALM: "CALM",
        BIT_INCONSIST: "INCONSIST",
        BIT_RESAMPLE: "RESAMPLE",
    }

    if pd.isna(bitmask):
        return "MISSING" if nan_as_missing else "NO_FLAG_VALUE"

    bitmask_int = int(bitmask)
    active = [name for bit, name in flags_map.items() if bitmask_int & bit]

    # Diagnósticos combinados avanzados
    if ("SPIKE" in active) and ("STEP" in active):
        active.append("<b>[HARD_FAIL: STEP+SPIKE]</b>")

    if k_critic is not None and pd.notna(severity) and severity > k_critic:
        active.append(f"<b>[HARD_FAIL: EXTREME_SPIKE (S={severity:.1f})]</b>")
    elif "SPIKE" in active and pd.notna(severity) and severity > 0:
        active.append(f"(Soft Spike S={severity:.1f})")

    return ", ".join(active) if active else "CLEAN"

def plot_tower_qc_interactive_from_netcdf(
    df_raw: Optional[pd.DataFrame],
    df_cleaned: pd.DataFrame,
    df_flags: pd.DataFrame,
    cfg: Any,
    height_m: float = 24.0,
    start_time: Optional[str] = None,  # <-- Nuevo parámetro: Fecha inicio ('YYYY-MM-DD HH:MM')
    end_time: Optional[str] = None,    # <-- Nuevo parámetro: Fecha fin ('YYYY-MM-DD HH:MM')
    max_points: int = 50000
) -> go.Figure:
    """Interactive forensic QC plot. 
    Allows filtering by a user-defined time interval before processing,
    preventing browser delays and memory overhead.
    """
    import warnings

    t_col = cfg.temp_cols.get(height_m)
    rh_col = cfg.rh_cols.get(height_m)
    w_col = cfg.wind_cols.get(height_m)

    if df_raw is None or df_raw.empty or len(df_raw.columns) == 0:
        warnings.warn("df_raw está vacío o no disponible. Usando datos limpios como respaldo.")
        df_raw = df_cleaned.copy()

    # 1. Sincronización e intersección base de marcas de tiempo
    common_idx = df_raw.index.intersection(df_cleaned.index).intersection(df_flags.index)
    if common_idx.empty:
        raise ValueError("Los DataFrames no comparten ninguna marca de tiempo.")

    # --- NUEVA SECCIÓN: RECORTE TEMPORAL DINÁMICO POR EL USUARIO ---
    if start_time is not None or end_time is not None:
        # Creamos una serie temporal temporal para usar el slicing rápido de Pandas
        temp_series = pd.Series(index=common_idx, dtype=float)
        try:
            # Pandas maneja de forma inteligente formatos parciales como '2024-01' o exactos '2024-01-15 14:00'
            temp_series = temp_series.loc[start_time:end_time]
            common_idx = temp_series.index
            if common_idx.empty:
                warnings.warn(f"El intervalo solicitado [{start_time} a {end_time}] no arrojó datos. Se graficará la serie completa.")
                # Si el filtro vacía el dataset, revertimos a la intersección completa por seguridad
                common_idx = df_raw.index.intersection(df_cleaned.index).intersection(df_flags.index)
        except Exception as e:
            warnings.warn(fr"Error al procesar el intervalo de tiempo ({e}). Asegúrese de usar formato 'YYYY-MM-DD'.")
    # ---------------------------------------------------------------

    # 2. Control de densidad por submuestreo de seguridad (Downsampling)
    total_records = len(common_idx)
    if total_records > max_points:
        step = int(np.ceil(total_records / max_points))
        warnings.warn(
            f"El intervalo seleccionado contiene {total_records:,} registros. "
            f"Se aplicó submuestreo sistemático (1 de cada {step} puntos) para proteger el navegador."
        )
        common_idx = common_idx[::step]

    # Segmentación final de los DataFrames optimizados
    df_raw_adj = df_raw.loc[common_idx]
    df_cleaned_adj = df_cleaned.loc[common_idx]
    flags_adj = df_flags.loc[common_idx]

    # Creación del lienzo multipanel compartiendo eje X
    fig = make_subplots(
        rows=3, cols=1,
        shared_xaxes=True,
        vertical_spacing=0.07,
        subplot_titles=(
            f"Air Temperature ({height_m} m)",
            f"Relative Humidity ({height_m} m)",
            f"Wind Speed ({height_m} m)",
        ),
    )

    plots_config = [
        (t_col, 1, "#EE6677", "temp"),
        (rh_col, 2, "#228833", "rh"),
        (w_col, 3, "#4477AA", "wind"),
    ]

    for col, row, color, vtype in plots_config:
        if col is None or col not in df_cleaned_adj.columns or col not in flags_adj.columns:
            continue

        actual_raw_col = df_raw_adj[col] if col in df_raw_adj.columns else df_cleaned_adj[col]

        # A. Curva de datos crudos (Fondo gris)
        fig.add_trace(
            go.Scatter(
                x=df_raw_adj.index, y=actual_raw_col,
                name=f"Raw {col}",
                line=dict(color="lightgrey", width=1),
                opacity=0.35,
                hoverinfo="skip",
                showlegend=True,
            ),
            row=row, col=1,
        )

        # B. Curva de datos limpios
        fig.add_trace(
            go.Scatter(
                x=df_cleaned_adj.index, y=df_cleaned_adj[col],
                name=f"Clean {col}",
                line=dict(color=color, width=2),
                mode="lines",
                hovertemplate="<b>VALOR LIMPIO</b><br>Valor: %{y:.2f}<br>Fecha: %{x}<extra></extra>"
            ),
            row=row, col=1,
        )

        # C. Puntos rechazados por Control de Calidad
        rejected_mask = actual_raw_col.notna() & df_cleaned_adj[col].isna()

        if rejected_mask.any():
            rej_x = df_raw_adj.index[rejected_mask]
            rej_y = actual_raw_col.loc[rejected_mask]

            sev_col = f"{col}_spike_severity"
            if sev_col in df_cleaned_adj.columns:
                severities = df_cleaned_adj.loc[rejected_mask, sev_col].fillna(0.0).values
            elif sev_col in flags_adj.columns:
                severities = flags_adj.loc[rejected_mask, sev_col].fillna(0.0).values
            else:
                severities = np.zeros(len(rej_x))

            k_norm = cfg.mad_k_by_var.get(vtype, 10.0)
            k_critic = k_norm * 3.0
            bitmasks = flags_adj.loc[rejected_mask, col].values

            rej_reasons = [
                get_flag_names(bitmask=b, severity=s, k_critic=k_critic)
                for b, s in zip(bitmasks, severities)
            ]

            fig.add_trace(
                go.Scatter(
                    x=rej_x, y=rej_y,
                    mode="markers",
                    name=f"Rejected {col}",
                    marker=dict(color="black", size=5, symbol="x-thin"),
                    text=rej_reasons,
                    hovertemplate=(
                        "<b>PUNTO RECHAZADO</b><br>"
                        "Valor Original: %{y:.2f}<br>"
                        "Diagnóstico: <b>%{text}</b><br>"
                        "Fecha: %{x}<extra></extra>"
                    ),
                ),
                row=row, col=1,
            )

    # Título dinámico que refleja el rango temporal actual en la gráfica
    rango_info = f"[{start_time if start_time else 'Inicio'} a {end_time if end_time else 'Fin'}]"
    fig.update_layout(
        height=900,
        title_text=fr"Auditoría Forense de Control de Calidad {rango_info} - Nivel {height_m} m",
        template="plotly_white",
        hovermode="x unified",
    )
    return fig


# %% Original notebook cell 5

# =============================================================================
# QC FLAG AUDIT - VERSION FINAL CORREGIDA, OPTIMIZADA Y CONSOLIDADA
# OGHYO Gradient Tower Dataset
# =============================================================================

# =============================================================================
# 0. DEFINICIÓN DE BITS QC (Sincronizado con TowerConfig)
# =============================================================================

BIT_MISSING = 1 << 0    # 1
BIT_RANGE = 1 << 1      # 2
BIT_STEP = 1 << 2       # 4
BIT_PERSIST = 1 << 3    # 8
BIT_SPIKE = 1 << 4      # 16
BIT_CALM = 1 << 5       # 32
BIT_INCONSIST = 1 << 6  # 64
BIT_RESAMPLE = 1 << 7   # 128

FLAG_ORDER = [
    ("MISSING", BIT_MISSING),
    ("RANGE", BIT_RANGE),
    ("STEP", BIT_STEP),
    ("PERSIST", BIT_PERSIST),
    ("SPIKE", BIT_SPIKE),
    ("CALM", BIT_CALM),
    ("INCONSIST", BIT_INCONSIST),
    ("RESAMPLE", BIT_RESAMPLE),
]

ALL_BITS = sum(bit for _, bit in FLAG_ORDER)


# =============================================================================
# 1. HELPERS DE TIEMPO Y COLUMNAS
# =============================================================================

def _dedup_index(
    df: pd.DataFrame,
    policy: Literal["first", "last", "mean", "median"] = "first"
) -> pd.DataFrame:
    """Resolve duplicated timestamps according to the selected policy."""
    if not isinstance(df.index, pd.DatetimeIndex):
        raise ValueError("The DataFrame index must be a DatetimeIndex.")

    if df.index.is_unique:
        return df

    if policy in ("first", "last"):
        return df[~df.index.duplicated(keep=policy)]

    if policy in ("mean", "median"):
        num = df.select_dtypes(include=[np.number]).groupby(level=0).agg(policy)
        non = df.select_dtypes(exclude=[np.number]).groupby(level=0).first()
        return num.join(non, how="outer").sort_index()

    raise ValueError("duplicate_policy must be one of: first, last, mean, median.")


def _normalize_time_index(
    df: pd.DataFrame,
    assume_local_tz: Optional[str] = None,
    round_freq: Optional[str] = None,
    duplicate_policy: Literal["first", "last", "mean", "median"] = "first"
) -> pd.DataFrame:
    """Normalize time index structure and timezone characteristics safely."""
    if not isinstance(df.index, pd.DatetimeIndex):
        raise ValueError("The DataFrame must have a DatetimeIndex.")

    out = df.copy()
    out.index = pd.to_datetime(out.index)

    if assume_local_tz is not None and out.index.tz is not None:
        out.index = out.index.tz_convert(assume_local_tz).tz_localize(None)

    out = out.sort_index()
    out = _dedup_index(out, duplicate_policy)

    if round_freq is not None:
        rounded_index = out.index.round(round_freq)
        out = out.groupby(rounded_index).last()
        out.index.name = df.index.name
        out = _dedup_index(out, duplicate_policy)

    return out


def _safe_flag_columns(
    flags_df: pd.DataFrame,
    data_df: Optional[pd.DataFrame] = None,
    columns: Optional[List[str]] = None,
    drop_non_flag_like: bool = True
) -> List[str]:
    """Safely determine which columns should be targeted for the audit process."""
    if columns is not None:
        cols = [c for c in columns if c in flags_df.columns]
    else:
        cols = list(flags_df.columns)

    if drop_non_flag_like:
        cols = [
            c for c in cols
            if not (
                str(c).endswith("_spike_severity")
                or str(c).startswith("q_")
                or str(c).startswith("theta_v_")
                or str(c) in {"time_utc", "P_Pa"}
            )
        ]

    if data_df is not None:
        cols = [c for c in cols if c in data_df.columns]

    return list(dict.fromkeys(cols))


# =============================================================================
# 2. HELPERS DE BITS
# =============================================================================

def _bit_label(v: int) -> str:
    """Convert integer bitmask into a human-readable combination string."""
    v = int(v)
    if v == 0:
        return "UNFLAGGED"

    labels = [name for name, bit in FLAG_ORDER if (v & bit) > 0]
    unknown = v & ~ALL_BITS
    if unknown:
        labels.append(f"UNKNOWN_BITS_{unknown}")

    return "+".join(labels) if labels else "UNKNOWN"


def _mask_any_bit(values: np.ndarray, bits: Iterable[int]) -> np.ndarray:
    """Return boolean mask where at least one selected bit is active."""
    values = np.asarray(values, dtype=np.int64)
    out = np.zeros(values.shape, dtype=bool)
    for bit in bits:
        out |= (values & bit) > 0
    return out


# =============================================================================
# 3. HELPERS CIRCULARES (Dirección del Viento)
# =============================================================================

def _circular_diff_deg(a: pd.Series, b: pd.Series) -> pd.Series:
    """Minimum signed angular difference a-b in degrees in [-180, 180)."""
    return ((a.astype(float) - b.astype(float) + 180.0) % 360.0) - 180.0


def _circular_abs_diff_deg(a: pd.Series, b: pd.Series) -> pd.Series:
    """Minimum absolute angular difference in degrees."""
    return _circular_diff_deg(a, b).abs()


def _rolling_circular_center_deg(s: pd.Series, window: int, min_periods: Optional[int] = None) -> pd.Series:
    """Rolling circular center based on atan2(mean(sin), mean(cos))."""
    if min_periods is None:
        min_periods = max(3, window // 2)

    rad = np.deg2rad(s.astype(float))
    sin_mean = np.sin(rad).rolling(window, center=True, min_periods=min_periods).mean()
    cos_mean = np.cos(rad).rolling(window, center=True, min_periods=min_periods).mean()
    ang = np.rad2deg(np.arctan2(sin_mean, cos_mean)) % 360.0
    return pd.Series(ang, index=s.index)


def _rolling_circular_mad_deg(s: pd.Series, window: int, center_deg: Optional[pd.Series] = None, min_periods: Optional[int] = None) -> pd.Series:
    """Rolling circular MAD around a circular rolling center."""
    if min_periods is None:
        min_periods = max(3, window // 2)
    if center_deg is None:
        center_deg = _rolling_circular_center_deg(s, window=window, min_periods=min_periods)

    dev = _circular_abs_diff_deg(s.astype(float), center_deg.astype(float))
    return dev.rolling(window, center=True, min_periods=min_periods).median()


# =============================================================================
# 4. SEVERIDAD ROBUSTA MAD (Cálculos Vectorizados)
# =============================================================================

def _calculate_mad_severity(s: pd.Series, window: int) -> pd.Series:
    """Calculate robust spike severity for scalar variables: |x - median| / MAD."""
    if window < 3 or window % 2 == 0:
        raise ValueError("mad_window must be >= 3 and odd.")

    s = pd.to_numeric(s, errors="coerce")
    min_periods = max(3, window // 2)

    med = s.rolling(window, center=True, min_periods=min_periods).median()
    dev = (s - med).abs()
    mad = dev.rolling(window, center=True, min_periods=min_periods).median()

    return dev / np.maximum(mad, 1e-12)


def _calculate_circular_mad_severity(s: pd.Series, window: int) -> pd.Series:
    """Calculate robust spike severity for circular wind direction variables."""
    if window < 3 or window % 2 == 0:
        raise ValueError("mad_window must be >= 3 and odd.")

    s = pd.to_numeric(s, errors="coerce")
    min_periods = max(3, window // 2)

    center = _rolling_circular_center_deg(s, window=window, min_periods=min_periods)
    dev = _circular_abs_diff_deg(s, center)
    mad = _rolling_circular_mad_deg(s, window=window, center_deg=center, min_periods=min_periods)

    return dev / np.maximum(mad, 1e-12)


# =============================================================================
# 5. POLÍTICA HARD-FAIL
# =============================================================================

def _compute_hard_fail_mask(flag_values: np.ndarray, hard_fail_bits: Iterable[int]) -> np.ndarray:
    """Compute hard-fail mask logic: RANGE OR (STEP AND SPIKE) OR active parameters."""
    flag_values = np.asarray(flag_values, dtype=np.int64)
    bits_tuple = tuple(hard_fail_bits) if hard_fail_bits is not None else ()

    hard_mask = np.zeros(flag_values.shape, dtype=bool)

    if BIT_RANGE in bits_tuple:
        hard_mask |= (flag_values & BIT_RANGE) > 0

    if BIT_STEP in bits_tuple and BIT_SPIKE in bits_tuple:
        hard_mask |= (((flag_values & BIT_STEP) > 0) & ((flag_values & BIT_SPIKE) > 0))

    if BIT_PERSIST in bits_tuple:
        hard_mask |= (flag_values & BIT_PERSIST) > 0

    if BIT_INCONSIST in bits_tuple:
        hard_mask |= (flag_values & BIT_INCONSIST) > 0

    return hard_mask


# =============================================================================
# 6. FUNCIÓN PRINCIPAL DE AUDITORÍA
# =============================================================================

def audit_flags_presence(
    flags_df: pd.DataFrame,
    data_df: Optional[pd.DataFrame] = None,
    columns: Optional[List[str]] = None,
    top_k_combos: int = 15,
    *,
    round_freq: Optional[str] = None,
    nearest_tol: Optional[str] = None,
    align: Literal["intersection", "union", "data_index", "flags_index"] = "intersection",
    assume_local_tz: Optional[str] = None,
    duplicate_policy: Literal["first", "last", "mean", "median"] = "first",
    hard_fail_bits: Optional[Iterable[int]] = None,
    mad_window: int = 21,
    include_all_cells_when_no_data_df: bool = True,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.Series, Dict[str, Any]]:
    """Audit QC flag presence, distribution, combinations, and hard-fail impact."""
    if not isinstance(flags_df.index, pd.DatetimeIndex):
        raise ValueError("flags_df must have a DatetimeIndex.")
    if data_df is not None and not isinstance(data_df.index, pd.DatetimeIndex):
        raise ValueError("data_df must have a DatetimeIndex.")

    bits_tuple = tuple(hard_fail_bits) if hard_fail_bits is not None else ()

    # 1. Normalización de tiempos
    F = _normalize_time_index(flags_df, assume_local_tz, round_freq, duplicate_policy)
    D = _normalize_time_index(data_df, assume_local_tz, round_freq, duplicate_policy) if data_df is not None else None

    # 2. Selección segura de columnas
    columns = _safe_flag_columns(flags_df=F, data_df=D, columns=columns, drop_non_flag_like=True)
    if not columns:
        raise ValueError("No valid columns to audit. Check configurations and source names.")

    F = F[columns]
    if D is not None:
        D = D[columns]

    # 3. Alineación Temporal
    if D is None:
        idx = F.index
        considered = pd.DataFrame(include_all_cells_when_no_data_df, index=idx, columns=columns, dtype=bool)
    elif nearest_tol is not None:
        D = D.sort_index()
        F = F.sort_index().reindex(D.index, method="nearest", tolerance=pd.Timedelta(nearest_tol))
        matched = ~F.isna().all(axis=1)
        F, D = F.loc[matched], D.loc[matched]
        considered = D.notna()
    else:
        if align == "intersection": idx = F.index.intersection(D.index)
        elif align == "union": idx = F.index.union(D.index)
        elif align == "data_index": idx = D.index
        elif align == "flags_index": idx = F.index
        F, D = F.reindex(idx), D.reindex(idx)
        considered = D.notna()

    F = F.apply(pd.to_numeric, errors="coerce").fillna(0).astype("int64")
    considered = considered.fillna(False).astype(bool)

    # 4. Auditoría a nivel de Celda
    per_col_rows = []
    for col in columns:
        mask_cons = considered[col].values
        flags_col = F[col].values
        n_cells = int(mask_cons.sum())

        rec = {"column": col, "cells_considered": n_cells}
        for name, bit in FLAG_ORDER:
            rec[name] = int((((flags_col & bit) > 0) & mask_cons).sum())

        rec["ANY"] = int((((flags_col & ALL_BITS) > 0) & mask_cons).sum())
        rec["UNFLAGGED"] = int(n_cells - rec["ANY"])

        hard_mask = _compute_hard_fail_mask(flags_col, bits_tuple) & mask_cons
        rec["HARD_FAIL"] = int(hard_mask.sum())
        rec["HARD_FAIL_pct"] = np.nan if n_cells == 0 else (100.0 * rec["HARD_FAIL"] / n_cells)

        # Diagnóstico robusto MAD integrado
        if D is not None and D[col].notna().any():
            try:
                is_wdir = str(col).lower().startswith("dir_wind")
                severity = _calculate_circular_mad_severity(D[col], mad_window) if is_wdir else _calculate_mad_severity(D[col], mad_window)
                spike_cells = (((flags_col & BIT_SPIKE) > 0) & mask_cons)
                
                if spike_cells.any():
                    vals = severity.values[spike_cells]
                    rec["spike_severity_mean"] = float(np.mean(vals))
                    rec["spike_severity_median"] = float(np.median(vals))
                    rec["spike_severity_max"] = float(np.max(vals))
                else:
                    rec["spike_severity_mean"] = rec["spike_severity_median"] = rec["spike_severity_max"] = np.nan
            except Exception:
                rec["spike_severity_mean"] = rec["spike_severity_median"] = rec["spike_severity_max"] = np.nan

        per_col_rows.append(rec)

    per_col_cells = pd.DataFrame(per_col_rows).set_index("column")
    for name in [n for n, _ in FLAG_ORDER] + ["ANY", "UNFLAGGED"]:
        per_col_cells[f"{name}_pct"] = 100.0 * per_col_cells[name] / per_col_cells["cells_considered"]

    # 5. Impacto temporal por Fila
    rows_total = len(F)
    rows_considered = int(considered.any(axis=1).sum())
    row_counts = []

    for name, bit in FLAG_ORDER:
        has_flag = np.any([((F[c].values & bit) > 0) & considered[c].values for c in columns], axis=0)
        row_counts.append({"flag": name, "rows_with_flag": int(has_flag.sum())})

    per_flag_rows = pd.DataFrame(row_counts).set_index("flag")
    per_flag_rows["rows_total"], per_flag_rows["rows_considered_total"] = rows_total, rows_considered
    per_flag_rows["rows_with_flag_pct_all_rows"] = 100.0 * per_flag_rows["rows_with_flag"] / rows_total
    per_flag_rows["rows_with_flag_pct_considered_rows"] = 100.0 * per_flag_rows["rows_with_flag"] / np.maximum(rows_considered, 1)

    # Hard fail a nivel de Fila
    has_hard = np.any([_compute_hard_fail_mask(F[c].values, bits_tuple) & considered[c].values for c in columns], axis=0)
    rows_with_hard = int(has_hard.sum())
    per_flag_rows.loc["HARD_FAIL"] = [rows_with_hard, rows_total, rows_considered, 100.0 * rows_with_hard / rows_total, 100.0 * rows_with_hard / np.maximum(rows_considered, 1)]

    # 6. Combinaciones de banderas celdas evaluadas
    vals_considered = F.values[considered.values]
    combos = pd.Series(vals_considered).map(_bit_label).value_counts().head(top_k_combos) if vals_considered.size > 0 else pd.Series(dtype="int64")

    # 7. Diagnósticos de metadata
    diagnostics = {
        "columns": columns, "n_columns": len(columns), "total_cells_considered": int(considered.values.sum()),
        "total_rows": rows_total, "align": f"nearest {nearest_tol}" if nearest_tol else align, "duplicate_policy": duplicate_policy
    }

    return per_col_cells, per_flag_rows, combos, diagnostics


# =============================================================================
# 7. FUNCIÓN AUXILIAR PARA USAR CON DATAFRAMES DESDE NETCDF
# =============================================================================

def prepare_qc_audit_inputs_from_netcdf(
    cleaned_from_nc: pd.DataFrame,
    flags_from_nc: pd.DataFrame,
    raw_from_nc: Optional[pd.DataFrame],
    cfg,
    include_wdir: bool = False,
) -> Tuple[pd.DataFrame, pd.DataFrame, List[str], Dict[str, Any]]:
    """Prepare consistent data inputs for audit_flags_presence targeting NetCDF structures."""
    base_cols = list(dict.fromkeys(list(cfg.temp_cols.values()) + list(cfg.rh_cols.values()) + list(cfg.wind_cols.values())))
    if include_wdir:
        base_cols += list(cfg.wdir_cols.values())

    if raw_from_nc is not None and not raw_from_nc.empty and len(raw_from_nc.columns) > 0:
        data_for_audit = raw_from_nc
        data_source = "raw_from_nc"
    else:
        data_for_audit = cleaned_from_nc
        data_source = "cleaned_from_nc_fallback"
        warnings.warn("raw_from_nc no disponible. Usando cleaned_from_nc como fallback operacional.", RuntimeWarning)

    cols_to_audit = [c for c in base_cols if c in flags_from_nc.columns and c in data_for_audit.columns]
    info = {"data_source": data_source, "n_columns_to_audit": len(cols_to_audit), "columns_to_audit": cols_to_audit}

    return data_for_audit, flags_from_nc, cols_to_audit, info


# =============================================================================
# 8. PRESENTACIÓN DE RESULTADOS
# =============================================================================

def print_qc_audit_report(
    per_col_cells: pd.DataFrame,
    per_flag_rows: pd.DataFrame,
    combos: pd.Series,
    diagnostics: Dict[str, Any],
    max_rows: Optional[int] = None,
) -> None:
    """Print QC audit report results in a clean, readable terminal format."""
    print("\n" + "="*50 + "\n=== REPORT DE AUDITORÍA DE CALIDAD METEOROLÓGICA ===\n" + "="*50)
    print("\n### 1. RESUMEN A NIVEL DE SENSOR (CELDAS CONSIDERADAS) ###")
    
    cols_show = [c for c in ["cells_considered", "ANY", "ANY_pct", "HARD_FAIL", "HARD_FAIL_pct", "UNFLAGGED", "UNFLAGGED_pct", "spike_severity_mean", "spike_severity_max"] if c in per_col_cells.columns]
    fmts_col = {c: (lambda x: f"{x:,.2f}%") for c in cols_show if c.endswith("_pct")}
    
    df_show = per_col_cells[cols_show]
    if max_rows is not None: df_show = df_show.head(max_rows)
    print(df_show.to_string(formatters=fmts_col))

    print("\n### 2. IMPACTO TEMPORAL EN REGISTROS (FILAS) ###")
    fmts_rows = {"rows_with_flag_pct_all_rows": lambda x: f"{x:,.2f}%", "rows_with_flag_pct_considered_rows": lambda x: f"{x:,.2f}%"}
    print(per_flag_rows[["rows_with_flag", "rows_total", "rows_with_flag_pct_all_rows"]].to_string(formatters=fmts_rows))

    print("\n### 3. COMBINACIONES DE MÁSCARAS DE ERROR MÁS COMUNES ###")
    print(combos)

    print("\n### 4. DIAGNÓSTICOS GLOBALES DEL PIPELINE ###")
    for key, value in diagnostics.items():
        print(f"  > {key}: {value}")


# =============================================================================
# 9. EJEMPLO DE EJECUCIÓN DEL PIPELINE COMPLETO INTEGRADO
# =============================================================================

if __name__ == "__main__":
    # Inicialización del objeto de configuración unificado (Bloque 1)
    cfg = TowerConfig()
    
    # Ruta del archivo NetCDF del proyecto
    nc_path = Path("data_nc/OGHYO_GradientTower_Dataset_2018_2026.nc")

    if not nc_path.exists():
        print(f"Aviso simulado: Coloque su archivo NetCDF real en '{nc_path.resolve()}'")
    else:
        # Ejecución del lector optimizado NumPy/Xarray (Bloque 2)
        # CORREGIDO: Llamada con el argumento unificado 'convert_to_local'
        cleaned_from_nc, flags_from_nc, raw_from_nc, ds, ds_raw = read_saved_tower_dataframes_from_netcdf(
            nc_file=str(nc_path),
            convert_to_local=True,
            remove_timezone=True,
        )

        # Preparación inteligente de variables climáticas
        data_for_audit, flags_for_audit, cols_to_audit, input_info = prepare_qc_audit_inputs_from_netcdf(
            cleaned_from_nc=cleaned_from_nc,
            flags_from_nc=flags_from_nc,
            raw_from_nc=raw_from_nc,
            cfg=cfg,
            include_wdir=False,
        )

        # Lanzamiento del motor analítico de banderas de calidad
        per_col_cells, per_flag_rows, combos, diag = audit_flags_presence(
            flags_df=flags_for_audit,
            data_df=data_for_audit,
            columns=cols_to_audit,
            top_k_combos=15,
            align="intersection",
            duplicate_policy=cfg.duplicate_policy,
            assume_local_tz=None,
            hard_fail_bits=cfg.hard_fail_bits,
            mad_window=cfg.mad_window,
        )

        # Imprimir el reporte completo estructurado en la consola
        print_qc_audit_report(
            per_col_cells=per_col_cells,
            per_flag_rows=per_flag_rows,
            combos=combos,
            diagnostics=diag,
        )


# %% Original notebook cell 6

# =============================================================================
# AUDITORÍA DE DISPONIBILIDAD Y GENERACIÓN DE CICLO DIURNO CIENTÍFICO
# OGHYO Gradient Tower Dataset - Módulo de Reporte Gráfico
# =============================================================================

# Importación de la estructura del primer bloque para asegurar consistencia
# (Asume que TowerConfig está definido en el mismo script o espacio de nombres)

def _infer_samples_per_hour(index: pd.DatetimeIndex) -> int:
    """Infer nominal samples per hour from the DatetimeIndex.

    Falls back to 60 if inference is not possible.
    """
    if len(index) < 2:
        return 60

    # Cambiado a .asi8 para evitar advertencias de desuso de view("int64") en Pandas recientes
    dt_sec = np.diff(index.asi8) / 1e9
    dt_sec = dt_sec[np.isfinite(dt_sec)]
    dt_sec = dt_sec[dt_sec > 0]

    if len(dt_sec) == 0:
        return 60

    step_sec = int(round(np.median(dt_sec)))
    if step_sec <= 0:
        return 60

    return max(1, int(round(3600 / step_sec)))


def audit_data_availability(df: pd.DataFrame, cfg: TowerConfig, threshold: float = 0.8) -> pd.DataFrame:
    """Realiza una auditoría de disponibilidad horaria y devuelve un DataFrame con los resultados."""
    if not isinstance(df.index, pd.DatetimeIndex):
        raise ValueError("El DataFrame debe tener un DatetimeIndex.")

    samples_per_hour = _infer_samples_per_hour(df.index)
    
    # Lógica de temporadas unificada (Sincronizada con el resto del pipeline)
    is_dry = df.index.month.isin([5, 6, 7, 8, 9])
    
    epochs = [
        (df.loc[is_dry], "Seca (May-Sep)"),
        (df.loc[~is_dry], "Lluviosa (Oct-Apr)")
    ]
    
    # Construcción segura de mapeos dinámicos desde la configuración de la torre
    all_mappings = {}
    for attr in ["temp_cols", "rh_cols", "wind_cols", "wdir_cols"]:
        mapping = getattr(cfg, attr, {})
        if mapping:
            all_mappings.update(mapping)
    
    print(f"\n{'='*70}")
    print(f"AUDITORÍA DE DISPONIBILIDAD HORARIA (Umbral: {threshold*100:.0f}%)")
    print(f"{'='*70}")

    all_results = []

    for data_epoch, title_epoch in epochs:
        if data_epoch.empty:
            continue
            
        n_days = data_epoch.index.normalize().nunique()
        expected_per_hour = max(1, n_days * samples_per_hour)
        
        epoch_results = []
        for height, col_name in all_mappings.items():
            if col_name not in data_epoch.columns:
                continue
            
            # Agrupación explícita por hora cronológica del índice
            counts = data_epoch[col_name].groupby(data_epoch.index.hour).count()
            counts = counts.reindex(range(24), fill_value=0)
            
            # Identificación de horas con pérdida crítica de datos
            hours_discarded = counts[counts / expected_per_hour < threshold].index.tolist()
            
            epoch_results.append({
                "Temporada": title_epoch,
                "Días_Evaluados": n_days,
                "Sensor": col_name,
                "Altura": f"{height}m",
                "Estado": "✅ OK" if not hours_discarded else f"⚠️ {len(hours_discarded)}h DESCARTADAS",
                "Horas_Afectadas": str(hours_discarded) if hours_discarded else "-"
            })
        
        audit_df = pd.DataFrame(epoch_results)
        print(f"\n>>> Estación: {title_epoch} ({n_days} días)")
        if not audit_df.empty:
            print(audit_df.drop(columns=["Temporada", "Días_Evaluados"]).to_string(index=False))
        
        all_results.extend(epoch_results)
            
    print(f"{'='*70}\n")
    
    return pd.DataFrame(all_results)


def _hourly_stats_linear(df: pd.DataFrame, cols: List[str]) -> Dict[str, pd.DataFrame]:
    """Compute hourly mean, std, count for linear physical variables."""
    out = {}
    for col in cols:
        if col not in df.columns:
            continue

        s = pd.to_numeric(df[col], errors="coerce")
        grp = s.groupby(df["hour"])
        stats = grp.agg(["mean", "std", "count"]).reindex(range(24))
        out[col] = stats

    return out


def _circular_mean_deg(series: pd.Series) -> float:
    """Circular mean implementation in degrees using vector native NumPy operations."""
    x = pd.to_numeric(series, errors="coerce").dropna().values
    if x.size == 0:
        return np.nan

    rad = np.deg2rad(x % 360.0)
    s = np.sin(rad).mean()
    c = np.cos(rad).mean()

    if np.isclose(s, 0.0) and np.isclose(c, 0.0):
        return np.nan

    return float(np.rad2deg(np.arctan2(s, c)) % 360.0)


def _circular_std_deg(series: pd.Series) -> float:
    """Circular standard deviation in degrees optimized for multi-level datasets."""
    x = pd.to_numeric(series, errors="coerce").dropna().values
    if x.size == 0:
        return np.nan

    rad = np.deg2rad(x % 360.0)
    s = np.sin(rad).mean()
    c = np.cos(rad).mean()
    R = np.sqrt(s**2 + c**2)

    if R <= 0 or R >= 1.0:
        return np.nan

    circ_std_rad = np.sqrt(-2.0 * np.log(R))
    return float(np.rad2deg(circ_std_rad))


def _hourly_stats_circular(df: pd.DataFrame, cols: List[str]) -> Dict[str, pd.DataFrame]:
    """Compute hourly circular mean, circular std, and valid count for angular variables."""
    out = {}
    for col in cols:
        if col not in df.columns:
            continue

        rows = []
        for hour in range(24):
            s = pd.to_numeric(df.loc[df["hour"] == hour, col], errors="coerce").dropna()

            if s.empty:
                rows.append({"mean": np.nan, "std": np.nan, "count": 0})
            else:
                rows.append({
                    "mean": _circular_mean_deg(s),
                    "std": _circular_std_deg(s),
                    "count": int(s.count())
                })

        out[col] = pd.DataFrame(rows, index=range(24))

    return out


def plot_diurnal_science_ready_with_wdir(
    df: pd.DataFrame,
    cfg: TowerConfig,
    threshold: float = 0.8,
    save_path: str = "figures_qc/diurnal_cycle_validated_with_wdir.png"
) -> None:
    """Generates a publication-quality diurnal cycle plot split by meteorological seasons.

    Fully unifies tracking for both linear variables and wind direction coordinates.
    """
    if not isinstance(df.index, pd.DatetimeIndex):
        raise ValueError("df must have a DatetimeIndex.")

    if not (0 < threshold <= 1):
        raise ValueError("threshold must be in the interval (0, 1].")

    # 1) Preparación de estructuras y aislamiento de columnas configuradas
    df_copy = df.copy().sort_index()

    temp_cols = [c for c in getattr(cfg, "temp_cols", {}).values() if c in df_copy.columns]
    rh_cols = [c for c in getattr(cfg, "rh_cols", {}).values() if c in df_copy.columns]
    wind_cols = [c for c in getattr(cfg, "wind_cols", {}).values() if c in df_copy.columns]
    wdir_cols = [c for c in getattr(cfg, "wdir_cols", {}).values() if c in df_copy.columns]

    cols_to_use = temp_cols + rh_cols + wind_cols + wdir_cols
    if not cols_to_use:
        raise ValueError("Ninguna de las columnas configuradas en la Torre fue hallada en el DataFrame.")

    df_copy = df_copy[cols_to_use].copy()
    df_copy["hour"] = df_copy.index.hour
    df_copy["date"] = df_copy.index.normalize()

    # Separación consistente de la serie por épocas climáticas (Seca vs Lluviosa)
    is_dry = df_copy.index.month.isin([5, 6, 7, 8, 9])
    
    epochs = [
        (df_copy.loc[is_dry], "Dry Season (May-Sep)"),
        (df_copy.loc[~is_dry], "Wet Season (Oct-Apr)")
    ]

    # 2) Configuración del Lienzo Científico (Matplotlib Context)
    with plt.rc_context({
        "font.size": 20,
        "axes.titlesize": 20,
        "axes.labelsize": 20,
        "xtick.labelsize": 20,
        "ytick.labelsize": 20
    }):
        var_groups = [
            (getattr(cfg, "temp_cols", {}), "Temperature (°C)", "linear"),
            (getattr(cfg, "rh_cols", {}), "Relative Humidity (%)", "linear"),
            (getattr(cfg, "wind_cols", {}), "Wind Speed (m/s)", "linear"),
            (getattr(cfg, "wdir_cols", {}), "Wind Direction (°)", "circular"),
        ]

        # Limpieza de subplots vacíos si alguna variable no cuenta con mapeo activo
        var_groups = [vg for vg in var_groups if vg[0]]
        n_rows = len(var_groups)

        fig, axes = plt.subplots(n_rows, 2, figsize=(16, 4 * n_rows), sharex=True, sharey="row")
        
        if n_rows == 1:
            axes = axes[np.newaxis, :]

        # Paleta de colores profesionales con alto contraste visual
        colors = ["#4477AA", "#66CCEE", "#CCBB44", "#EE6677", "#228833", "#AA3377"]
        markers = ["o", "s", "^", "D", "v", "P"]

        samples_per_hour = _infer_samples_per_hour(df_copy.index)

        # 3) Procesamiento Estadístico Avanzado y Graficación por Época
        for col_idx, (data_epoch, title_epoch) in enumerate(epochs):
            if data_epoch.empty:
                continue

            n_days = data_epoch["date"].nunique()
            expected_per_hour = max(1, n_days * samples_per_hour)

            l_cols = [c for c in temp_cols + rh_cols + wind_cols if c in data_epoch.columns]
            c_cols = [c for c in wdir_cols if c in data_epoch.columns]

            hourly_stats_linear = _hourly_stats_linear(data_epoch, l_cols)
            hourly_stats_circular = _hourly_stats_circular(data_epoch, c_cols)

            for row_idx, (mapping, ylabel, vtype) in enumerate(var_groups):
                ax = axes[row_idx, col_idx]

                for i, (height, col_name) in enumerate(mapping.items()):
                    if col_name not in data_epoch.columns:
                        continue

                    stats = hourly_stats_circular.get(col_name) if vtype == "circular" else hourly_stats_linear.get(col_name)
                    if stats is None:
                        continue

                    # Filtro estricto de disponibilidad mínima por hora cronológica
                    mask = (stats["count"] / expected_per_hour) >= threshold
                    m = stats["mean"].where(mask)
                    s = stats["std"].where(mask)
                    hours = stats.index.to_numpy()

                    color = colors[i % len(colors)]
                    marker = markers[i % len(markers)]

                    # Traza de la curva promedio principal
                    ax.plot(
                        hours, m.to_numpy(dtype=float),
                        label=f"{height} m", color=color, marker=marker,
                        markersize=5, lw=1.8, zorder=3
                    )

                    # Banda sombreada de variabilidad física (Desviación Estándar)
                    ax.fill_between(
                        hours, 
                        (m - s).to_numpy(dtype=float), 
                        (m + s).to_numpy(dtype=float),
                        color=color, alpha=0.10, zorder=2
                    )

                    # Anotación científica automática de extremos locales (Máximos y Mínimos)
                    valid_m = m.dropna()
                    if not valid_m.empty:
                        idx_max, val_max = valid_m.idxmax(), valid_m.max()
                        idx_min, val_min = valid_m.idxmin(), valid_m.min()

                        for idx, val, offset, va in [(idx_max, val_max, 7, "bottom"), (idx_min, val_min, -7, "top")]:
                            ax.scatter([idx], [val], color=color, s=20, zorder=5, edgecolor="black", linewidth=0.4)
                            ax.annotate(
                                f"{val:.1f}", xy=(idx, val), xytext=(0, offset),
                                textcoords="offset points", ha="center", va=va,
                                fontsize=8, color=color, fontweight="bold", zorder=6
                            )

                # Formateo técnico de rejillas y etiquetas de ejes
                if row_idx == 0:
                    ax.set_title(f"{title_epoch} ({n_days} days)", fontweight="bold", pad=12)
                if col_idx == 0:
                    ax.set_ylabel(ylabel, fontweight="bold", labelpad=8)
                
                # Ajustes fijos de límites físicos lógicos
                if "Humidity" in ylabel:
                    ax.set_ylim(-5, 105)
                elif "Wind Direction" in ylabel:
                    ax.set_ylim(-10, 370)
                    ax.set_yticks(np.arange(0, 361, 90))

                ax.grid(True, linestyle=":", alpha=0.5)
                ax.text(
                        0.02, 0.04, fr"Avail $\geq$ {threshold*100:.0f}%",  # <--- Añadida la 'r' para hacerla Raw String
                        transform=ax.transAxes, ha="left", va="bottom", fontsize=15, alpha=0.5,
                        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=1)
                        )

        # Configuración final del eje temporal (X)
        for ax in axes[-1, :]:
            ax.set_xlabel("Local Time (Hour)", fontweight="bold", labelpad=8)
            ax.set_xticks(range(0, 24, 2))
            ax.set_xlim(-0.5, 23.5)

        # Extracción limpia de la leyenda para evitar duplicación entre paneles
        handles, labels = None, None
        for ax in fig.axes:
            h, l = ax.get_legend_handles_labels()
            if h:
                handles, labels = h, l
                break

        if handles:
            fig.legend(
                handles, labels, loc="lower center", bbox_to_anchor=(0.5, -0.01),
                ncol=max(1, len(labels)), title="Sensor Height AGL (meters)",
                frameon=False, fontsize=20, title_fontsize=20
            )

        # Ajuste de márgenes para prevenir superposición de textos científicos
        fig.tight_layout(rect=[0, 0.05, 1, 1], h_pad=1.0, w_pad=1.0)

        # Almacenamiento seguro en disco
        save_dir = os.path.dirname(save_path)
        if save_dir:
            os.makedirs(save_dir, exist_ok=True)

        plt.savefig(save_path, bbox_inches="tight", dpi=600)
        plt.show()


# %% Original notebook cell 7

# =============================================================================
# PERFILES VERTICALES ESTACIONALES PARA PUBLICACIÓN CIENTÍFICA
# OGHYO Gradient Tower Dataset - Módulo de Perfiles Avanzados
# =============================================================================

# --- CONFIGURACIÓN GLOBAL DE FUENTES PARA PUBLICACIÓN ---
plt.rcParams.update({
    "text.usetex": False,            # Cambiar a True solo si tienes LaTeX instalado en el sistema
    "mathtext.fontset": "stix",      # STIX es muy similar a Times New Roman y estándar en journals
    "font.family": "serif",          # Usar fuentes con serifa para el cuerpo del texto
    "font.serif": ["Times New Roman", "DejaVu Serif"], 
    "axes.labelweight": "normal",
    "axes.titleweight": "bold",
    "xtick.direction": "in",         # Ticks hacia adentro (estilo clásico de publicación)
    "ytick.direction": "in",
    "axes.grid": True,
    "grid.linestyle": "--",
    "grid.alpha": 0.3
})


def plot_seasonal_vertical_profiles_publication(
    df: pd.DataFrame, 
    cfg: TowerConfig, 
    save_prefix: str = "figures_qc/seasonal_profile"
) -> None:
    """Generates multi-level vertical profiles of thermodynamics variables

    Uses a layout optimized for high-impact scientific journals.
    """
    if df.empty:
        raise ValueError("El DataFrame de entrada está vacío.")

    # 1. Definición unificada de temporadas climáticas
    month_array = df.index.month
    is_dry = (month_array >= 5) & (month_array <= 9)
    seasons = [(df.loc[is_dry], "Dry Season"), (df.loc[~is_dry], "Wet Season")]

    heights = cfg.heights_m
    
    # Estructura del Layout (Título, Símbolo LaTeX, Diccionario Config, Unidades, Factor Escala)
    plot_config = [
        ("Temperature", r"$T$", cfg.temp_cols, r"^\circ\mathrm{C}", 1.0), 
        ("Virtual Potential Temperature", r"$\theta_v$", "theta_v", r"\mathrm{K}", 1.0),
        ("Specific Humidity", r"$q$", "q", r"10^{-3} \, \mathrm{kg} \, \mathrm{kg}^{-1}", 1000.0)
    ]

    hours_to_plot = [0, 4, 8, 12, 16, 20]
    
    for df_season, season_name in seasons:
        if df_season.empty: 
            continue
            
        hourly_means = df_season.groupby(df_season.index.hour).mean(numeric_only=True)

        fig, axes = plt.subplots(3, 1, figsize=(10, 13), constrained_layout=True)
        
        cmap = plt.get_cmap("inferno")
        colors = [cmap((i / 24) * 0.8 + 0.1) for i in hours_to_plot]

        for ax, (title, symbol, col_source, units, scale) in zip(axes, plot_config):
            all_vals = [] 
            
            for hr, color in zip(hours_to_plot, colors):
                if hr not in hourly_means.index: 
                    continue
                
                vals, v_heights = [], []
                for h in heights:
                    # Selección e identificación segura del nombre de columna según el Bloque de Configuración
                    if isinstance(col_source, dict):
                        col_name = col_source.get(h)
                    else:
                        # Para variables derivadas generadas con sufijo de altura estandarizado (q, theta_v)
                        suffix = str(int(h)) if float(h).is_integer() else str(h).replace(".", "p")
                        col_name = f"{col_source}_{suffix}"
                    
                    if col_name and col_name in hourly_means.columns:
                        val = hourly_means.loc[hr, col_name]
                        if pd.notna(val):
                            vals.append(val * scale)
                            v_heights.append(h)
                
                if vals:
                    all_vals.extend(vals)
                    ax.plot(vals, v_heights, marker='o', lw=1.8, color=color, 
                            markersize=6, label=f"{hr:02d}:00", zorder=3)
                    
                    # Anotación horaria refinada en formato Raw String para LaTeX seguro
                    ax.text(vals[-1], v_heights[-1] + 0.6, fr"$\mathbf{{{hr:02d}h}}$", 
                            color=color, ha='center', fontsize=9)

            # Estilo técnico de los ejes del panel
            ax.set_title(title, loc='left', fontsize=12, fontweight='bold')
            ax.set_xlabel(fr"{symbol} $({units})$", fontsize=15)
            ax.set_ylabel(r"Height $(\mathrm{m \, AGL})$", fontsize=15)
            
            ax.set_ylim(0, max(heights) + 5)
            ax.set_yticks(heights)
            
            ax.tick_params(axis='both', which='major', labelsize=15, length=5, width=1.0)
            ax.xaxis.set_major_formatter(FormatStrFormatter('%.1f'))

            if all_vals:
                vmin, vmax = min(all_vals), max(all_vals)
                pad = (vmax - vmin) * 0.15 if vmax != vmin else 1.0
                ax.set_xlim(vmin - pad, vmax + pad)

        fig.suptitle(f"Vertical Profiles: {season_name}", fontsize=15, fontweight='bold', y=1.01)
        
        save_dir = os.path.dirname(save_prefix)
        if save_dir: 
            os.makedirs(save_dir, exist_ok=True)
            
        clean_name = season_name.lower().replace(" ", "_")
        plt.savefig(f"{save_prefix}_{clean_name}.png", dpi=600, bbox_inches="tight")
        plt.show()


def plot_seasonal_wind_profiles_publication(
    df: pd.DataFrame, 
    cfg: TowerConfig, 
    save_prefix: str = "figures_qc/seasonal_wind"
) -> None:
    """Generates vertical profiles for wind speed and robust diurnal circular stats for wind direction."""
    if df.empty:
        return

    month_array = df.index.month
    is_dry = (month_array >= 5) & (month_array <= 9)
    seasons = [(df.loc[is_dry], "Dry Season"), (df.loc[~is_dry], "Wet Season")]

    heights = cfg.heights_m
    hours_to_plot = [0, 4, 8, 12, 16, 20]
    
    # Extraer de manera segura la columna de dirección de viento (usualmente a 24m)
    wdir_col = next(iter(cfg.wdir_cols.values()), None)
    
    for df_season, season_name in seasons:
        if df_season.empty: 
            continue
        
        # --- PROCESAMIENTO KINEMÁTICO AVANZADO ---
        # Separación y cálculo lineal para velocidad
        df_copy = df_season.copy()
        df_copy["hour"] = df_copy.index.hour
        
        ws_cols = [c for c in cfg.wind_cols.values() if c in df_copy.columns]
        hourly_ws_means = df_copy.groupby("hour")[ws_cols].mean()

        # Corrección metodológica: Estadísticas de dirección usando funciones circulares del Bloque 3
        stats_circular_wd = {}
        if wdir_col and wdir_col in df_copy.columns:
            for hr in range(24):
                subset = df_copy.loc[df_copy["hour"] == hr, wdir_col].dropna()
                stats_circular_wd[hr] = {
                    "mean": _circular_mean_deg(subset),
                    "std": _circular_std_deg(subset)
                }

        fig = plt.figure(figsize=(10, 13), constrained_layout=True)
        gs = fig.add_gridspec(2, 1, height_ratios=[1.3, 1])
        ax_ws = fig.add_subplot(gs[0])
        ax_wd = fig.add_subplot(gs[1])

        cmap = plt.get_cmap("inferno")
        colors = [cmap((i / 24) * 0.8 + 0.1) for i in hours_to_plot]

        # --- PANEL 1: Velocidad del Viento (Perfil de Altura) ---
        all_ws = []
        for hr, color in zip(hours_to_plot, colors):
            if hr not in hourly_ws_means.index: 
                continue
            vals, v_heights = [], []
            for h in heights:
                col_name = cfg.wind_cols.get(h)
                if col_name and col_name in hourly_ws_means.columns:
                    val = hourly_ws_means.loc[hr, col_name]
                    if pd.notna(val):
                        vals.append(val)
                        v_heights.append(h)
            if vals:
                all_ws.extend(vals)
                ax_ws.plot(vals, v_heights, marker='o', lw=1.8, color=color, markersize=6)
                ax_ws.text(vals[-1], v_heights[-1] + 0.6, fr"$\mathbf{{{hr:02d}h}}$", color=color, ha='center', fontsize=9)

        ax_ws.set_title("Wind Speed", loc='left', fontsize=14, fontweight='bold')
        ax_ws.set_xlabel(r"$WS \ (\mathrm{m \, s^{-1}})$", fontsize=15)
        ax_ws.set_ylabel(r"Height $(\mathrm{m \, AGL})$", fontsize=15)
        ax_ws.set_yticks(heights)
        ax_ws.set_ylim(0, max(heights) + 5)
        ax_ws.tick_params(axis='both', which='major', labelsize=15, length=5, width=1.0)
        ax_ws.xaxis.set_major_formatter(FormatStrFormatter('%.1f'))

        # --- PANEL 2: Dirección del Viento Cíclica ---
        if stats_circular_wd:
            full_hours = sorted(stats_circular_wd.keys())
            means = np.array([stats_circular_wd[h]["mean"] for h in full_hours])
            stds = np.array([stats_circular_wd[h]["std"] for h in full_hours])
            
            # Reemplazar valores NaN por ceros funcionales para sombreado continuo
            means_clean = np.nan_to_num(means, nan=0.0)  # <--- Añadido el '_'
            stds_clean = np.nan_to_num(stds, nan=0.0)   # <--- Añadido el '_'
            
            # Sombreado de variabilidad física angular
            ax_wd.fill_between(full_hours, means_clean - stds_clean, means_clean + stds_clean, color='gray', alpha=0.12, zorder=0)
            ax_wd.plot(full_hours, means, color='gray', lw=1, ls='--', alpha=0.4, zorder=1)
            
            for hr, color in zip(hours_to_plot, colors):
                if hr in stats_circular_wd and pd.notna(stats_circular_wd[hr]["mean"]):
                    m = stats_circular_wd[hr]["mean"]
                    s = stats_circular_wd[hr]["std"]
                    
                    ax_wd.errorbar(hr, m, yerr=s if pd.notna(s) else 0, fmt='none', ecolor=color, elinewidth=1.8, capsize=2.5, zorder=2)
                    ax_wd.scatter(hr, m, color=color, s=70, edgecolors='black', linewidths=0.5, zorder=3)
                    
                    ax_wd.text(hr + 0.35, m, f"{m:.0f}°", color=color, va='center', fontsize=9, fontweight='bold')
                    ax_wd.text(hr, m + (s if pd.notna(s) else 15) + 12, fr"$\mathbf{{{hr:02d}h}}$", color=color, ha='center', fontsize=8)
            
            # Identificación explícita de la altura del instrumento anemométrico superior
            z_top = [k for k, v in cfg.wdir_cols.items() if v == wdir_col][0]
            ax_wd.set_title(fr"Wind Direction Routine at {int(z_top)}m AGL ($\mu_{{circ}} \pm \sigma_{{circ}}$)", loc='left', fontsize=12, fontweight='bold')
            ax_wd.set_xlabel("Local Time (Hour)", fontsize=15)
            ax_wd.set_ylabel(r"Direction $(^\circ)$", fontsize=15)
            ax_wd.set_xticks(hours_to_plot)
            ax_wd.set_yticks([0, 90, 180, 270, 360])
            ax_wd.set_yticklabels(['0° (N)', '90° (E)', '180° (S)', '270° (W)', '360° (N)'])
            ax_wd.set_xlim(-1, 25)
            ax_wd.set_ylim(-15, 415)
            ax_wd.tick_params(axis='both', which='major', labelsize=14, length=5, width=1.0)

        fig.suptitle(f"Seasonal Analysis: {season_name}", fontsize=14, fontweight='bold', y=1.01)
        
        save_dir = os.path.dirname(save_prefix)
        if save_dir: 
            os.makedirs(save_dir, exist_ok=True)
            
        clean_name = season_name.lower().replace(" ", "_")
        plt.savefig(f"{save_prefix}_{clean_name}.png", dpi=400, bbox_inches="tight")
        plt.show()


# %% Original notebook cell 8

# =============================================================================
# EXPORTADOR AVANZADO DE ESTADÍSTICAS AGREGADAS A NETCDF (ESTÁNDAR CF-1.8)
# OGHYO Gradient Tower Dataset
# =============================================================================

# Se asume que TowerConfig, _circular_mean_deg y _circular_std_deg están
# declarados en el entorno o importados desde los bloques anteriores.


def infer_samples_per_period(index: pd.DatetimeIndex, period: str = "30min") -> int:
    """Infer the expected number of samples per aggregation period.

    Uses optimized low-level properties (.asi8) to avoid deprecation warnings.
    """
    if len(index) < 2:
        return int(pd.Timedelta(period).total_seconds() // 60)

    dt_sec = np.diff(index.asi8) / 1e9
    dt_sec = dt_sec[np.isfinite(dt_sec)]
    dt_sec = dt_sec[dt_sec > 0]

    if len(dt_sec) == 0:
        return int(pd.Timedelta(period).total_seconds() // 60)

    sample_step_sec = int(round(np.median(dt_sec)))
    period_sec = int(pd.Timedelta(period).total_seconds())

    if sample_step_sec <= 0:
        return max(1, int(period_sec // 60))

    return max(1, int(round(period_sec / sample_step_sec)))


def sanitize_netcdf_name(name: str) -> str:
    """Convert a DataFrame column name into a safe NetCDF variable name."""
    return (
        str(name)
        .replace(" ", "_")
        .replace("/", "_")
        .replace("-", "_")
        .replace(".", "_")
        .replace("(", "")
        .replace(")", "")
    )


def get_variable_units(col: str) -> str:
    """Assign standard SI units matching the CF convention based on column prefixes."""
    col = str(col)
    if col.startswith("temp"):
        return "degree_C"
    if col.startswith("RH"):
        return "%"
    if col.startswith("wind"):
        return "m s-1"
    if col.startswith("dir_wind"):
        return "degree"
    if col.startswith("q_"):
        return "kg kg-1"
    if col.startswith("theta_v"):
        return "K"
    return "unknown"


def get_variable_long_name(col: str) -> str:
    """Assign descriptive metadata labels to variables written into the NetCDF."""
    col = str(col)
    if col.startswith("temp"):
        return f"air temperature statistics for {col}"
    if col.startswith("RH"):
        return f"relative humidity statistics for {col}"
    if col.startswith("wind"):
        return f"wind speed statistics for {col}"
    if col.startswith("dir_wind"):
        return f"wind direction statistics for {col}"
    if col.startswith("q_"):
        return f"specific humidity statistics for {col}"
    if col.startswith("theta_v"):
        return f"virtual potential temperature statistics for {col}"
    return f"statistics for {col}"


def detect_wind_direction_columns(df: pd.DataFrame, cfg: Optional[TowerConfig] = None) -> list:
    """Detect wind direction columns unrolling the TowerConfig maps safely."""
    if cfg is not None and hasattr(cfg, "wdir_cols"):
        return [col for col in cfg.wdir_cols.values() if col in df.columns]

    return [col for col in df.columns if str(col).lower().startswith("dir_wind")]


# =============================================================================
# 2. FUNCIÓN PRINCIPAL DE EXPORTACIÓN Y AGREGACIÓN
# =============================================================================

def save_30min_statistics_to_netcdf(
    cleaned_df: pd.DataFrame,
    output_nc: str,
    cfg: Optional[TowerConfig] = None,
    period: str = "30min",
    timezone_local: str = "America/Lima",
    store_time_as_utc: bool = True,
    global_attrs: Optional[Dict[str, Any]] = None,
) -> xr.Dataset:
    """Time-aggregates high-frequency climate tower data into a robust NetCDF data structure."""
    if not isinstance(cleaned_df.index, pd.DatetimeIndex):
        raise ValueError("cleaned_df debe tener un DatetimeIndex válido.")
    if cleaned_df.empty:
        raise ValueError("El DataFrame cleaned_df está vacío.")
    if pd.Timedelta(period).total_seconds() <= 0:
        raise ValueError("El parámetro period debe reflejar una frecuencia válida positiva.")

    df = cleaned_df.copy().sort_index()

    # 1. Conversión forzada y segura a tipos de datos numéricos flotantes
    numeric_df = pd.DataFrame(index=df.index)
    for col in df.columns:
        numeric_df[col] = pd.to_numeric(df[col], errors="coerce")

    cols_to_process = [col for col in numeric_df.columns if numeric_df[col].notna().any()]
    if not cols_to_process:
        raise ValueError("No se encontraron variables con registros numéricos válidos para procesar.")

    numeric_df = numeric_df[cols_to_process]
    wdir_cols = detect_wind_direction_columns(numeric_df, cfg=cfg)
    expected_samples = infer_samples_per_period(numeric_df.index, period=period)

    # 2. Resampling temporal estructurado de matrices estadísticas
    resampler = numeric_df.resample(period)
    
    # Inicialización acelerada de estructuras vacías con índices temporales correctos
    resample_index = resampler.mean().index
    mean_df = pd.DataFrame(index=resample_index)
    std_df = pd.DataFrame(index=resample_index)
    min_df = pd.DataFrame(index=resample_index)
    max_df = pd.DataFrame(index=resample_index)
    count_df = pd.DataFrame(index=resample_index)

    for col in cols_to_process:
        s = numeric_df[col]
        col_resampler = s.resample(period)

        if col in wdir_cols:
            # Vinculación metodológica con las funciones matemáticas optimizadas de NumPy (Bloque 3)
            mean_df[col] = col_resampler.apply(_circular_mean_deg)
            std_df[col] = col_resampler.apply(_circular_std_deg)
            # Los extremos angulares se manejan de manera lineal diagnóstica bajo advertencia de metadato
            min_df[col] = col_resampler.min()
            max_df[col] = col_resampler.max()
        else:
            mean_df[col] = col_resampler.mean()
            std_df[col] = col_resampler.std()
            min_df[col] = col_resampler.min()
            max_df[col] = col_resampler.max()
            
        count_df[col] = col_resampler.count()

    expected_df = pd.DataFrame(expected_samples, index=resample_index, columns=cols_to_process)
    availability_df = (100.0 * count_df / expected_df).clip(lower=0.0, upper=100.0)

    # 3. Alineación e internacionalización del eje temporal de coordenadas
    time_index = resample_index
    if store_time_as_utc:
        if time_index.tz is None:
            time_coord = time_index.tz_localize(timezone_local).tz_convert("UTC").tz_localize(None)
        else:
            time_coord = time_index.tz_convert("UTC").tz_localize(None)
            
        time_attrs = {
            "standard_name": "time",
            "axis": "T",
            "long_name": f"Start time of each {period} aggregation interval in UTC",
            "timezone_original": timezone_local,
            "timezone_stored": "UTC",
        }
    else:
        time_coord = time_index.tz_localize(None) if time_index.tz is not None else time_index
        time_attrs = {
            "standard_name": "time",
            "axis": "T",
            "long_name": f"Start time of each {period} aggregation interval in local time",
            "timezone_stored": timezone_local,
        }

    # 4. Construcción del objeto integrado xarray Dataset
    ds_out = xr.Dataset(
        coords={
            "time": xr.DataArray(time_coord, dims=("time",), attrs=time_attrs)
        }
    )

    statistic_tables = {
        "mean": mean_df,
        "std": std_df,
        "min": min_df,
        "max": max_df,
        "valid_count": count_df,
        "expected_count": expected_df,
        "availability_pct": availability_df,
    }

    # 5. Volcado e inyección de variables físicas y capas de diagnóstico
    for col in cols_to_process:
        safe_col = sanitize_netcdf_name(col)
        units = get_variable_units(col)
        long_name = get_variable_long_name(col)
        is_wdir = col in wdir_cols

        for stat_name, table in statistic_tables.items():
            var_name = f"{safe_col}_{stat_name}"

            if stat_name in ["valid_count", "expected_count"]:
                values = table[col].to_numpy(dtype=np.int32)
                stat_units = "1"
            elif stat_name == "availability_pct":
                values = table[col].to_numpy(dtype=float)
                stat_units = "%"
            else:
                values = table[col].to_numpy(dtype=float)
                stat_units = units

            # Generación de trazabilidad procedimental de metadatos (Provenance mapping)
            if stat_name == "mean":
                method = "circular mean" if is_wdir else "arithmetic mean"
            elif stat_name == "std":
                method = "circular standard deviation" if is_wdir else "sample standard deviation"
            elif stat_name in ["min", "max"] and is_wdir:
                method = "linear observed angular extremum; diagnostic only for circular data"
            elif stat_name == "availability_pct":
                method = "100 * valid_count / expected_count"
            else:
                method = stat_name

            ds_out[var_name] = xr.DataArray(
                values,
                dims=("time",),
                coords={"time": ds_out["time"]},
                attrs={
                    "units": stat_units,
                    "long_name": f"{period} {stat_name} of {long_name}",
                    "aggregation_period": period,
                    "original_variable": str(col),
                    "statistic": stat_name,
                    "method": method,
                }
            )

    # 6. Atributos globales del archivo (Estándares Internacionales COARDS/CF)
    ds_out.attrs.update({
        "title": f"{period} Statistics from Cleaned Meteorological Tower Data",
        "summary": (
            f"This NetCDF file contains {period} mean, standard deviation, "
            f"minimum, maximum, valid sample count, expected sample count, and "
            f"availability percentage for each numeric variable in the cleaned "
            f"meteorological tower dataset."
        ),
        "institution": "Instituto Geofísico del Perú (IGP)",
        "source_dataframe": "cleaned_from_nc",
        "processing_level": "Aggregated statistics from quality-controlled data",
        "aggregation_period": period,
        "expected_samples_per_period": int(expected_samples),
        "availability_percentage_definition": "100 * valid_count / expected_count",
        "linear_statistics": "Arithmetic mean, sample standard deviation, minimum, and maximum",
        "circular_statistics": (
            "Circular mean and circular standard deviation were used for wind "
            "direction variables. Minimum and maximum wind direction values are "
            "stored as linear observed extrema and should be interpreted cautiously."
        ),
        "wind_direction_columns": ", ".join(wdir_cols) if wdir_cols else "None detected",
        "time_interval_label": "left",
        "time_interval_closed": "left",
        # CORREGIDO: Uso del estándar moderno de zona horaria explícita para evitar DeprecationWarnings
        "created": f"{datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z')}",
        "Conventions": "CF-1.8",
    })

    if global_attrs:
        ds_out.attrs.update(global_attrs)

    # 7. Configuración de codecs de compresión y guardado físico en disco
    output_dir = os.path.dirname(output_nc)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    encoding = {
        var: {"zlib": True, "complevel": 4} for var in ds_out.data_vars
    }
    encoding["time"] = {
        "units": "seconds since 1970-01-01 00:00:00",
        "calendar": "proleptic_gregorian",
        "dtype": "int64",
    }

    ds_out.to_netcdf(
        output_nc,
        format="NETCDF4",
        engine="netcdf4",
        mode="w",
        encoding=encoding,
    )

    print(f"NetCDF guardado exitosamente en: {output_nc}")
    print(f"Número de variables finales procesadas: {len(ds_out.data_vars)}")
    return ds_out


# %% Original notebook cell 9

# =============================================================================
# WORKFLOW DE EJECUCIÓN MAESTRO, AUDITADO Y CONSOLIDADO
# OGHYO Gradient Tower Dataset
# =============================================================================

def create_output_dir(path: str) -> None:
    """Create a directory if the path is not empty."""
    if path:
        os.makedirs(path, exist_ok=True)


def save_reconstructed_dataframes_pickle(
    cleaned_from_nc: pd.DataFrame,
    flags_from_nc: pd.DataFrame,
    raw_from_nc: Optional[pd.DataFrame] = None,
    out_dir: str = "output_df",
) -> Dict[str, str]:
    """Safely export reconstructed DataFrames to optimized binary pickle files."""
    os.makedirs(out_dir, exist_ok=True)
    outputs = {}
    items = {
        "cleaned_from_nc": cleaned_from_nc,
        "flags_from_nc": flags_from_nc,
        "raw_from_nc": raw_from_nc,
    }
    for name, df in items.items():
        if df is None or df.empty:
            continue
        path = os.path.join(out_dir, f"{name}.pkl")
        df.to_pickle(path)
        outputs[name] = path
    return outputs


def run_full_qc_audit_workflow(
    nc_file: str,
    cfg: Optional[TowerConfig] = None,
    *,
    local_tz: str = "America/Lima",
    remove_timezone: bool = True,
    include_wdir: bool = False,  # Seteado en False por compatibilidad con wd_qc_flags ausentes en tu NetCDF
    audit_data_source: Literal["raw", "cleaned"] = "raw",
    top_k_combos: int = 15,
) -> Dict[str, Any]:
    """Run the complete audited workflow from NetCDF reading to QC flag summaries.

    Coordinates all decoupled infrastructure layers in a deterministic pipeline,
    guaranteeing complete trace integrity without modifying state globals.
    """
    # 1. Resolver instancia de configuración centralizada
    if cfg is None:
        cfg = make_default_tower_config()

    # 2. Extracción optimizada desde NetCDF (Bloque 2)
    cleaned_from_nc, flags_from_nc, raw_from_nc, ds, ds_raw = read_saved_tower_dataframes_from_netcdf(
        nc_file=nc_file,
        convert_to_local=True,
        local_tz=local_tz,
        remove_timezone=remove_timezone,
    )

    # 3. Preparación e interconexión inteligente de variables climáticas (Bloque 4)
    # Sincronizado: Esta función devuelve una tupla fija de 4 elementos de forma estricta.
    data_df, flags_df, columns, input_info = prepare_qc_audit_inputs_from_netcdf(
        cleaned_from_nc=cleaned_from_nc,
        flags_from_nc=flags_from_nc,
        raw_from_nc=raw_from_nc if audit_data_source == "raw" else None,
        cfg=cfg,
        include_wdir=include_wdir,
    )

    # 4. Lanzamiento del motor analítico estadístico de banderas de calidad (Bloque 4)
    # Ajuste crítico: assume_local_tz se pasa como None porque el lector ya entregó la serie en local naive time.
    per_col_cells, per_flag_rows, combos, diagnostics = audit_flags_presence(
        flags_df=flags_df,
        data_df=data_df,
        columns=columns,
        top_k_combos=top_k_combos,
        align="intersection",
        assume_local_tz=None, 
        duplicate_policy=cfg.duplicate_policy,
        hard_fail_bits=cfg.hard_fail_bits,
        mad_window=cfg.mad_window,
    )

    # 5. Consolidación del diccionario final de metadatos y proveniencia
    diagnostics = dict(diagnostics)
    diagnostics.update({
        "audit_data_source_requested": audit_data_source,
        "input_preparation_summary": input_info,
        "hard_fail_policy": "RANGE OR (STEP AND SPIKE); PERSIST/INCONSIST only if explicitly included",
    })

    return {
        "cfg": cfg,
        "cleaned_from_nc": cleaned_from_nc,
        "flags_from_nc": flags_from_nc,
        "raw_from_nc": raw_from_nc,
        "ds": ds,
        "ds_raw": ds_raw,
        "flags_df_audit": flags_df,
        "data_df_audit": data_df,
        "columns_audited": columns,
        "per_col_cells": per_col_cells,
        "per_flag_rows": per_flag_rows,
        "combos": combos,
        "diagnostics": diagnostics,
    }


def print_workflow_summary(results: Dict[str, Any]) -> None:
    """Print a compact summary of the integrated workflow results directly to terminal."""
    # Inspección de integridad estructural de dataframes de xarray reconstruidos
    inspect_reconstructed_dataframes(
        results["cleaned_from_nc"],
        results["flags_from_nc"],
        results.get("raw_from_nc"),
    )
    
    # Renderizado del reporte ejecutivo analítico por consola
    print_qc_audit_report(
        per_col_cells=results["per_col_cells"],
        per_flag_rows=results["per_flag_rows"],
        combos=results["combos"],
        diagnostics=results["diagnostics"],
    )
