from __future__ import annotations
#

"""QC Gradient Tower optimized audited pipeline.

Extracted from: D:/OneDrive/PAPER_GRADIENT_TOWER/PYTHON_PIPELINE/QC_GRADIENT_TOWER_OPTIMIZED_AUDITED.ipynb
Generated by Codex on 2026-05-25.
"""


# %% Original notebook cell 1


from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import os
import warnings

import numpy as np
import pandas as pd

try:
    import xarray as xr
except ModuleNotFoundError:
    xr = None

try:
    from astral import LocationInfo
    from astral.sun import sun
except ImportError:
    LocationInfo = None
    sun = None


def require_xarray():
    """Return xarray or raise a clear dependency error."""
    if xr is None:
        raise ModuleNotFoundError(
            "El pipeline QC requiere xarray para exportar NetCDF. "
            "Instale las dependencias con: pip install -r requirements.txt"
        )
    return xr


def require_astral():
    """Return Astral helpers or raise a clear dependency error."""
    if LocationInfo is None or sun is None:
        raise ModuleNotFoundError(
            "El pipeline QC requiere astral para calcular sunrise. "
            "Instale las dependencias con: pip install -r requirements.txt"
        )
    return LocationInfo, sun


# %% Original notebook cell 3

# =============================================================================
# CONFIGURACIÓN DE ARCHIVOS
# =============================================================================
TEMP_CALIB_FILE = "calib_txt/matrix_temp_met.dat"
RH_CALIB_FILE = "calib_txt/matrix_relhum_met.dat"
TOWER_MAT_FILE = "input_mat/var_torre_30m_20180515_20260331.mat"
SUN_MAT_FILE = "input_mat/sun_position_20180515_20260331.mat"
OUTPUT_NETCDF = "data_nc/OGHYO_GradientTower_Dataset_2018_2026.nc"

# Configuración geográfica para sunrise
SITE_NAME = "Huancayo"
SITE_REGION = "Peru"
SITE_TIMEZONE = "America/Lima"
SITE_LAT = -12.0
SITE_LON = -75.3

# Si True, el pipeline falla cuando faltan columnas esperadas.
# Si False, crea columnas faltantes como NaN y las marca como MISSING.
STRICT_COLUMNS = True


# %% Original notebook cell 5

# =============================================================================
# CONSTANTES FÍSICAS
# =============================================================================
KAPPA = 0.4
G = 9.80665
RD = 287.05
RV = 461.5
CP = 1004.67
P0 = 101325.0
T0_STD = 288.15
LAPSE = 0.0065

# =============================================================================
# QC FLAGS BITMASK
# =============================================================================
BIT_MISSING   = 1 << 0   # 1
BIT_RANGE     = 1 << 1   # 2
BIT_STEP      = 1 << 2   # 4
BIT_PERSIST   = 1 << 3   # 8
BIT_SPIKE     = 1 << 4   # 16
BIT_CALM      = 1 << 5   # 32
BIT_INCONSIST = 1 << 6   # 64
BIT_RESAMPLE  = 1 << 7   # 128

BIT_NAMES = {
    BIT_MISSING: "missing",
    BIT_RANGE: "range",
    BIT_STEP: "step",
    BIT_PERSIST: "persistence",
    BIT_SPIKE: "spike",
    BIT_CALM: "calm",
    BIT_INCONSIST: "inconsistency",
    BIT_RESAMPLE: "resample",
}

FLAG_MASKS_CF = np.array(
    [BIT_MISSING, BIT_RANGE, BIT_STEP, BIT_PERSIST, BIT_SPIKE, BIT_CALM, BIT_INCONSIST, BIT_RESAMPLE],
    dtype=np.int32,
)
FLAG_MEANINGS_CF = "missing range step persistence spike calm inconsistency resample"
FLAG_COMMENT_CF = "A value of 0 means PASS / no QC flag."


def require_file(path: str | Path) -> Path:
    """Return a Path if it exists; otherwise raise a clear FileNotFoundError."""
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"No existe el archivo requerido: {p.resolve()}")
    return p


def ensure_parent_dir(path: str | Path) -> None:
    """Create parent directory for a file path if needed."""
    parent = Path(path).expanduser().resolve().parent
    parent.mkdir(parents=True, exist_ok=True)


def flatten_mat_array(obj: object, name: str) -> np.ndarray:
    """Convert a MATLAB variable to a 1-D numpy array."""
    arr = np.asarray(obj).squeeze()
    if arr.ndim == 0:
        arr = arr.reshape(1)
    return arr.ravel()


# %% Original notebook cell 7

def read_calibration_matrix(path: str | Path, n_sensors: int = 6) -> pd.DataFrame:
    """
    Read calibration matrix with at least three columns.

    Expected columns by position:
        column 0: sensor/id or unused field
        column 1: slope m
        column 2: intercept b
    """
    p = require_file(path)
    df = pd.read_csv(p, header=None, sep=r"\s+", engine="python")
    if df.shape[0] < n_sensors or df.shape[1] < 3:
        raise ValueError(
            f"La matriz de calibración {p} debe tener al menos {n_sensors} filas y 3 columnas. "
            f"Forma encontrada: {df.shape}"
        )
    df = df.iloc[:n_sensors, :3].copy()
    df.columns = ["sensor", "m", "b"]
    df["m"] = pd.to_numeric(df["m"], errors="coerce")
    df["b"] = pd.to_numeric(df["b"], errors="coerce")
    if df[["m", "b"]].isna().any().any():
        raise ValueError(f"La matriz de calibración {p} contiene coeficientes no numéricos.")
    return df


def calibration_dict(calib_df: pd.DataFrame, prefix: str, n_sensors: int = 6) -> Dict[str, Tuple[float, float]]:
    """Build {column_name: (m, b)} for temp_n1..temp_n6 or RH_n1..RH_n6."""
    return {
        f"{prefix}{i+1}": (float(calib_df.loc[i, "m"]), float(calib_df.loc[i, "b"]))
        for i in range(n_sensors)
    }


def load_mat_file(path: str | Path) -> dict:
    """Load a MATLAB file with a clear validation message."""
    p = require_file(path)
    try:
        import scipy.io
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "El pipeline QC requiere scipy para leer archivos .mat. "
            "Instale las dependencias con: pip install -r requirements.txt"
        ) from exc
    try:
        return scipy.io.loadmat(p)
    except Exception as exc:
        raise RuntimeError(f"No se pudo leer el archivo MAT: {p.resolve()}") from exc


def require_mat_keys(mat: dict, keys: Sequence[str], label: str) -> None:
    """Validate that expected keys exist in a MATLAB dict."""
    missing = [k for k in keys if k not in mat]
    if missing:
        raise KeyError(f"Faltan variables en {label}: {missing}")


# %% Original notebook cell 9

TOWER_REQUIRED_KEYS = [
    "year_data", "month_data", "day_data", "hour_data", "min_data", "seg_data",
    "temp_n1", "temp_n2", "temp_n3", "temp_n4", "temp_n5", "temp_n6",
    "RH_n1", "RH_n2", "RH_n3", "RH_n4", "RH_n5", "RH_n6",
    "wind_n1", "wind_n2", "wind_n3", "wind_n4", "wind_n5", "wind_n6",
    "dir_wind_02",
]
SUN_REQUIRED_KEYS = ["zenith_angle", "azimuth_angle"]


def build_tower_dataframe_from_mat(
    tower_mat: dict,
    sun_mat: dict,
    temp_calib: Dict[str, Tuple[float, float]],
    rh_calib: Dict[str, Tuple[float, float]],
) -> pd.DataFrame:
    """
    Build the calibrated tower DataFrame from MATLAB dictionaries.

    This performs the same logical operations as the original notebook:
    - extracts time, radiation geometry, temperature, RH, wind and wind direction;
    - applies linear calibration to temperature and RH;
    - preserves NaN values for subsequent QC instead of dropping complete rows.
    """
    require_mat_keys(tower_mat, TOWER_REQUIRED_KEYS, "archivo de torre")
    require_mat_keys(sun_mat, SUN_REQUIRED_KEYS, "archivo de posición solar")

    data = {
        "year_tower": flatten_mat_array(tower_mat["year_data"], "year_data"),
        "month_tower": flatten_mat_array(tower_mat["month_data"], "month_data"),
        "day_tower": flatten_mat_array(tower_mat["day_data"], "day_data"),
        "hour_tower": flatten_mat_array(tower_mat["hour_data"], "hour_data"),
        "min_tower": flatten_mat_array(tower_mat["min_data"], "min_data"),
        "sec_tower": flatten_mat_array(tower_mat["seg_data"], "seg_data"),
        "zenith_tower": flatten_mat_array(sun_mat["zenith_angle"], "zenith_angle"),
        "azimuth_tower": flatten_mat_array(sun_mat["azimuth_angle"], "azimuth_angle"),
        "dir_wind": flatten_mat_array(tower_mat["dir_wind_02"], "dir_wind_02"),
    }

    for i in range(1, 7):
        data[f"temp_n{i}"] = flatten_mat_array(tower_mat[f"temp_n{i}"], f"temp_n{i}")
        data[f"RH_n{i}"] = flatten_mat_array(tower_mat[f"RH_n{i}"], f"RH_n{i}")
        data[f"wind_n{i}"] = flatten_mat_array(tower_mat[f"wind_n{i}"], f"wind_n{i}")

    lengths = {k: len(v) for k, v in data.items()}
    if len(set(lengths.values())) != 1:
        raise ValueError(
            "Longitudes inconsistentes entre variables. "
            "El código original con zip habría truncado datos silenciosamente. "
            f"Longitudes encontradas: {lengths}"
        )

    df = pd.DataFrame(data)
    df.replace("", np.nan, inplace=True)

    # Convert all sensor/time columns to numeric where possible.
    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Apply temperature calibration: y = m*x + b
    for col, (m, b) in temp_calib.items():
        if col in df.columns:
            df[col] = df[col] * m + b

    # Apply RH calibration: y = m*x + b
    for col, (m, b) in rh_calib.items():
        if col in df.columns:
            df[col] = df[col] * m + b

    return df


# %% Original notebook cell 11

def add_datetime_and_sunrise(
    df: pd.DataFrame,
    timezone: str = "America/Lima",
    site_name: str = "Huancayo",
    site_region: str = "Peru",
    latitude: float = -12.0,
    longitude: float = -75.3,
    duplicate_policy: str = "first",
) -> pd.DataFrame:
    """
    Add local Datetime index and sunrise time.

    The output keeps the same main variables as the original notebook but fixes
    duplicate handling by timestamp instead of whole-row duplication.
    """
    required_time_cols = ["year_tower", "month_tower", "day_tower", "hour_tower", "min_tower", "sec_tower"]
    missing = [c for c in required_time_cols if c not in df.columns]
    if missing:
        raise KeyError(f"Faltan columnas temporales: {missing}")

    out = df.copy()

    # Keep rows with valid time components only. Sensor NaNs are preserved for QC.
    out = out.dropna(subset=required_time_cols)

    dt_aux = out[required_time_cols].rename(
        columns={
            "year_tower": "year",
            "month_tower": "month",
            "day_tower": "day",
            "hour_tower": "hour",
            "min_tower": "minute",
            "sec_tower": "second",
        }
    )

    for col in dt_aux.columns:
        dt_aux[col] = pd.to_numeric(dt_aux[col], errors="coerce").astype("Int64")

    dt_local = pd.to_datetime(dt_aux, errors="coerce")
    valid_dt = dt_local.notna()
    if not valid_dt.all():
        warnings.warn(f"Se eliminarán {(~valid_dt).sum()} filas con fecha/hora inválida.")
        out = out.loc[valid_dt].copy()
        dt_local = dt_local.loc[valid_dt]

    dt_local = dt_local.dt.tz_localize(timezone)
    out["Datetime"] = dt_local

    location_info, sun_func = require_astral()
    city = location_info(site_name, site_region, timezone, latitude, longitude)
    days_local = dt_local.dt.date
    unique_days = pd.unique(days_local)

    sunrise_map = {}
    for d in unique_days:
        sunrise_map[d] = sun_func(city.observer, date=d, tzinfo=timezone)["sunrise"]

    out["sunrise"] = [sunrise_map[d].time() for d in days_local]

    out = out.set_index("Datetime").sort_index()

    if not out.index.is_unique:
        if duplicate_policy in {"first", "last"}:
            out = out[~out.index.duplicated(keep=duplicate_policy)]
        elif duplicate_policy in {"mean", "median"}:
            num = out.select_dtypes(include=[np.number]).groupby(level=0).agg(duplicate_policy)
            non = out.select_dtypes(exclude=[np.number]).groupby(level=0).first()
            out = pd.concat([num, non], axis=1).sort_index()
        else:
            raise ValueError("duplicate_policy debe ser first, last, mean o median.")

    out = out.drop(columns=required_time_cols, errors="ignore")

    # Normalize wind direction to [0, 360) while preserving NaN.
    if "dir_wind" in out.columns:
        out["dir_wind"] = pd.to_numeric(out["dir_wind"], errors="coerce") % 360.0

    return out


def summarize_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    """Return NaN counts and percentages per column."""
    if len(df) == 0:
        return pd.DataFrame(columns=["nan_count", "nan_pct"])
    summary = pd.DataFrame({
        "nan_count": df.isna().sum(),
        "nan_pct": 100.0 * df.isna().mean(),
    }).sort_values("nan_pct", ascending=False)
    return summary


# %% Original notebook cell 13

def hypsometric_pressure(alt_m: float, T0: float = T0_STD, lapse: float = LAPSE, p0: float = P0) -> float:
    """Pressure from altitude using a standard-atmosphere hypsometric relation."""
    if alt_m < 0:
        raise ValueError("alt_m must be non-negative.")
    if lapse <= 0:
        raise ValueError("lapse must be positive.")
    base = 1.0 - lapse * alt_m / T0
    if base <= 0:
        raise ValueError("Invalid combination of alt_m, T0, and lapse.")
    expn = G / (RD * lapse)
    return float(p0 * base ** expn)


def es_tetens_pa(T_C: np.ndarray | pd.Series) -> np.ndarray:
    """Saturation vapor pressure over water using Tetens formula, in Pa."""
    T_C = np.asarray(T_C, dtype=float)
    return 610.94 * np.exp(17.625 * T_C / (T_C + 243.04))


def mixing_ratio(P: np.ndarray | float, e: np.ndarray | float) -> np.ndarray:
    """Mixing ratio r = 0.622 e / (P - e). Invalid denominators become NaN."""
    P = np.asarray(P, dtype=float)
    e = np.asarray(e, dtype=float)
    denom = P - e
    return np.where(denom > 0, 0.622 * e / denom, np.nan)


def specific_humidity_from_r(r: np.ndarray | pd.Series) -> np.ndarray:
    """Specific humidity q from mixing ratio r."""
    r = np.asarray(r, dtype=float)
    return np.where(r >= 0, r / (1.0 + r), np.nan)


def virtual_potential_temperature(T_C: np.ndarray, q: np.ndarray, P: np.ndarray | float) -> np.ndarray:
    """Virtual potential temperature in K."""
    T_K = np.asarray(T_C, dtype=float) + 273.15
    q = np.asarray(q, dtype=float)
    P = np.asarray(P, dtype=float)
    theta = T_K * (P0 / P) ** (RD / CP)
    return theta * (1.0 + 0.61 * q)


def circular_diff_deg(a: pd.Series, b: pd.Series) -> pd.Series:
    """Minimum signed angular difference a-b in degrees in [-180, 180)."""
    return ((a - b + 180.0) % 360.0) - 180.0


def circular_abs_diff_deg(a: pd.Series, b: pd.Series) -> pd.Series:
    """Minimum absolute angular difference in degrees."""
    return circular_diff_deg(a, b).abs()


def rolling_circular_center_deg(s: pd.Series, window: int, min_periods: Optional[int] = None) -> pd.Series:
    """Rolling circular center based on atan2(mean(sin), mean(cos))."""
    if min_periods is None:
        min_periods = max(3, window // 2)
    s_float = s.astype(float)
    rad = np.deg2rad(s_float)
    sin_mean = np.sin(rad).rolling(window, center=True, min_periods=min_periods).mean()
    cos_mean = np.cos(rad).rolling(window, center=True, min_periods=min_periods).mean()
    ang = np.rad2deg(np.arctan2(sin_mean, cos_mean)) % 360.0
    return pd.Series(ang, index=s.index)


def rolling_circular_mad_deg(
    s: pd.Series,
    window: int,
    center_deg: Optional[pd.Series] = None,
    min_periods: Optional[int] = None,
) -> pd.Series:
    """Rolling circular median absolute deviation around a circular center."""
    if min_periods is None:
        min_periods = max(3, window // 2)
    if center_deg is None:
        center_deg = rolling_circular_center_deg(s, window, min_periods=min_periods)
    dev = circular_abs_diff_deg(s.astype(float), center_deg.astype(float))
    return dev.rolling(window, center=True, min_periods=min_periods).median()


def rolling_median(s: pd.Series, window: int, min_periods: Optional[int] = None) -> pd.Series:
    if min_periods is None:
        min_periods = max(3, window // 2)
    return s.rolling(window, center=True, min_periods=min_periods).median()


def rolling_mad(s: pd.Series, window: int, min_periods: Optional[int] = None) -> pd.Series:
    if min_periods is None:
        min_periods = max(3, window // 2)
    med = rolling_median(s, window, min_periods=min_periods)
    dev = (s - med).abs()
    return dev.rolling(window, center=True, min_periods=min_periods).median()


# %% Original notebook cell 15

@dataclass
class TowerConfig:
    heights_m: List[float] = field(default_factory=lambda: [2.0, 6.0, 12.0, 24.0])

    temp_cols: Dict[float, str] = field(default_factory=lambda: {
        2.0: "temp_n1", 6.0: "temp_n2", 12.0: "temp_n3", 24.0: "temp_n5"
    })
    rh_cols: Dict[float, str] = field(default_factory=lambda: {
        2.0: "RH_n1", 6.0: "RH_n2", 12.0: "RH_n3", 24.0: "RH_n5"
    })
    wind_cols: Dict[float, str] = field(default_factory=lambda: {
        2.0: "wind_n1", 6.0: "wind_n2", 12.0: "wind_n3", 24.0: "wind_n5"
    })
    wdir_cols: Dict[float, str] = field(default_factory=lambda: {24.0: "dir_wind"})

    site_altitude_m: float = 3315.0
    timezone: str = "America/Lima"
    naive_are_local: bool = True
    duplicate_policy: str = "first"
    sample_period_s: Optional[int] = None
    target_freq: Optional[str] = "1min"
    strict_columns: bool = True

    ranges: Dict[str, Tuple[float, float]] = field(default_factory=lambda: {
        "temp": (-20.0, 40.0),
        "rh": (0.0, 100.0),
        "wind": (0.0, 50.0),
        "wdir": (0.0, 360.0),
    })

    step_limits: Dict[str, float] = field(default_factory=lambda: {
        "temp": 1.5,
        "rh": 8.0,
        "wind": 5.0,
        "wdir": 90.0,
    })

    persistence_eps: Dict[str, float] = field(default_factory=lambda: {
        "temp": 0.1,
        "rh": 0.2,
        "wind": 0.05,
        "wdir": 2.0,
    })
    persistence_min_samples: int = 20

    mad_window: int = 21
    mad_k_by_var: Dict[str, float] = field(default_factory=lambda: {
        "temp": 5.0,
        "rh": 6.0,
        "wind": 10.0,
        "wdir": 10.0,
    })

    # Minimum absolute deviation required to flag spikes when MAD is zero.
    # This avoids over-flagging tiny resolution changes over flat windows.
    zero_mad_min_dev: Dict[str, float] = field(default_factory=lambda: {
        "temp": 0.2,
        "rh": 1.0,
        "wind": 0.2,
        "wdir": 5.0,
    })

    calm_ws_ms: float = 0.2

    # Elimina RANGE siempre; STEP y SPIKE eliminan solo cuando coinciden.
    hard_fail_bits: Tuple[int, ...] = (BIT_RANGE, BIT_STEP, BIT_SPIKE)
    remove_persistence: bool = False
    remove_rh_inconsistency: bool = False

    # Optional outputs
    save_clean_csv: Optional[str] = None
    save_flags_csv: Optional[str] = None
    save_summary_csv: Optional[str] = None
    save_clean_parquet: Optional[str] = None
    save_flags_parquet: Optional[str] = None
    save_summary_parquet: Optional[str] = None

    def __post_init__(self) -> None:
        if not self.heights_m:
            raise ValueError("heights_m must not be empty.")
        if len(set(self.heights_m)) != len(self.heights_m):
            raise ValueError("heights_m contains duplicate heights.")
        if self.site_altitude_m < 0:
            raise ValueError("site_altitude_m must be non-negative.")
        if self.mad_window < 3 or self.mad_window % 2 == 0:
            raise ValueError("mad_window must be odd and >= 3.")
        if self.persistence_min_samples < 2:
            raise ValueError("persistence_min_samples must be >= 2.")
        if self.calm_ws_ms < 0:
            raise ValueError("calm_ws_ms must be non-negative.")
        if self.duplicate_policy not in {"first", "last", "mean", "median"}:
            raise ValueError("duplicate_policy must be first, last, mean or median.")

        for v in ("temp", "rh", "wind", "wdir"):
            for attr in ("ranges", "step_limits", "persistence_eps", "mad_k_by_var", "zero_mad_min_dev"):
                if v not in getattr(self, attr):
                    raise ValueError(f"Missing {attr} definition for '{v}'.")
            lo, hi = self.ranges[v]
            if lo > hi:
                raise ValueError(f"Invalid range for {v}: lower bound > upper bound.")
            if self.mad_k_by_var[v] <= 0:
                raise ValueError(f"mad_k_by_var[{v}] must be positive.")

        heights_set = set(self.heights_m)
        for name, mapping in {
            "temp_cols": self.temp_cols,
            "rh_cols": self.rh_cols,
            "wind_cols": self.wind_cols,
            "wdir_cols": self.wdir_cols,
        }.items():
            for z in mapping:
                if z not in heights_set:
                    raise ValueError(f"Height {z} in {name} is not present in heights_m.")


# %% Original notebook cell 17

def fix_index_and_tz(
    df: pd.DataFrame,
    tz_local: str = "America/Lima",
    naive_are_local: bool = True,
    duplicate_policy: str = "first",
) -> pd.DataFrame:
    """Ensure DatetimeIndex, localize/convert timezone, sort, and resolve duplicates by timestamp."""
    if not isinstance(df.index, pd.DatetimeIndex):
        raise ValueError("The DataFrame index must be a DatetimeIndex.")

    out = df.copy()
    idx = out.index

    if idx.tz is None:
        idx = idx.tz_localize(tz_local if naive_are_local else "UTC")
    elif naive_are_local:
        idx = idx.tz_convert(tz_local)

    out.index = idx
    out = out.sort_index()

    if not out.index.is_unique:
        if duplicate_policy in {"first", "last"}:
            out = out[~out.index.duplicated(keep=duplicate_policy)]
        elif duplicate_policy in {"mean", "median"}:
            num = out.select_dtypes(include=[np.number]).groupby(level=0).agg(duplicate_policy)
            non = out.select_dtypes(exclude=[np.number]).groupby(level=0).first()
            out = pd.concat([num, non], axis=1).sort_index()
        else:
            raise ValueError("duplicate_policy must be first, last, mean or median.")

    return out


def infer_sample_period_s(idx: pd.DatetimeIndex) -> Optional[int]:
    """Infer sample period in seconds using median positive time difference."""
    if len(idx) < 2:
        return None
    diffs = idx.to_series().diff().dropna().dt.total_seconds()
    diffs = diffs[diffs > 0]
    if diffs.empty:
        return None
    return int(round(float(diffs.median())))


def set_flag(flags: pd.DataFrame, col: str, mask: pd.Series, bit: int) -> None:
    """Set a bit flag in a flag DataFrame with index-safe alignment."""
    if col not in flags.columns:
        raise KeyError(f"Column {col} not found in flags DataFrame.")
    mask = mask.reindex(flags.index).fillna(False).astype(bool)
    flags.loc[mask, col] = flags.loc[mask, col].astype("int32") | np.int32(bit)


def has_any_bit(flag_series: pd.Series, bits: Iterable[int]) -> pd.Series:
    """Return True where any selected bits are present."""
    vals = flag_series.fillna(0).astype("int64")
    out = pd.Series(False, index=flag_series.index)
    for bit in bits:
        out |= (vals & bit) > 0
    return out


def decode_flag_value(value: int) -> List[str]:
    """Decode a bitmask integer into readable flag names."""
    value = int(value)
    if value == 0:
        return ["pass"]
    return [name for bit, name in BIT_NAMES.items() if (value & bit) > 0]


# %% Original notebook cell 19

def apply_range_check(s: pd.Series, rng: Tuple[float, float]) -> pd.Series:
    """Flag values outside [lo, hi]. NaN is handled by BIT_MISSING separately."""
    lo, hi = rng
    return ((s < lo) | (s > hi)).fillna(False)


def apply_step_check(
    s: pd.Series,
    max_step: Optional[float],
    vtype: str,
    sample_period_s: Optional[int] = None,
) -> pd.Series:
    """Flag excessive changes between consecutive samples."""
    if max_step is None:
        return pd.Series(False, index=s.index)

    if vtype == "wdir":
        diff = circular_abs_diff_deg(s.astype(float), s.astype(float).shift(1))
    else:
        diff = s.astype(float).diff().abs()

    fail = diff > max_step

    # Avoid flagging jumps across large temporal gaps when index is irregular.
    if isinstance(s.index, pd.DatetimeIndex) and sample_period_s is not None:
        dt = s.index.to_series().diff().dt.total_seconds()
        fail &= dt <= 1.5 * sample_period_s

    return fail.fillna(False)


def apply_persistence_check(s: pd.Series, eps: float, min_samples: int, vtype: str) -> pd.Series:
    """Flag periods with near-constant signal over a rolling window."""
    s_float = s.astype(float)
    if min_samples < 2:
        return pd.Series(False, index=s.index)

    if vtype == "wdir":
        center = rolling_circular_center_deg(s_float, min_samples, min_periods=min_samples)
        dev = circular_abs_diff_deg(s_float, center)
        roll_amp = dev.rolling(min_samples, center=True, min_periods=min_samples).max()
        flat = roll_amp <= eps
    else:
        roll_max = s_float.rolling(min_samples, center=True, min_periods=min_samples).max()
        roll_min = s_float.rolling(min_samples, center=True, min_periods=min_samples).min()
        flat = (roll_max - roll_min) <= eps

    return flat.fillna(False)


def apply_spike_mad_check(
    s: pd.Series,
    window: int,
    k: float,
    vtype: str,
    zero_mad_min_dev: float,
) -> Tuple[pd.Series, pd.Series]:
    """Robust spike detection using rolling median and MAD."""
    s_float = s.astype(float)
    valid = s_float.notna()

    if vtype == "wdir":
        center = rolling_circular_center_deg(s_float, window)
        mad = rolling_circular_mad_deg(s_float, window, center_deg=center)
        dev = circular_abs_diff_deg(s_float, center)
    else:
        center = rolling_median(s_float, window)
        mad = rolling_mad(s_float, window)
        dev = (s_float - center).abs()

    severity = pd.Series(np.nan, index=s.index, dtype=float)
    positive_mad = mad > 0
    severity.loc[positive_mad] = dev.loc[positive_mad] / mad.loc[positive_mad]

    fail = ((mad > 0) & (dev / mad > k))
    fail |= ((mad <= 0) & (dev > zero_mad_min_dev))
    fail &= valid

    return fail.fillna(False), severity


def rh_internal_consistency(temp_C: pd.Series, rh: pd.Series) -> pd.Series:
    """
    True where dew point exceeds air temperature.

    RH is not clipped here because out-of-range RH should remain physically visible.
    RANGE flags separately identify RH outside 0-100 %.
    """
    temp_arr = temp_C.to_numpy(dtype=float)
    rh_arr = rh.to_numpy(dtype=float)
    es = es_tetens_pa(temp_arr)
    e = (rh_arr / 100.0) * es

    with np.errstate(divide="ignore", invalid="ignore"):
        ln_ratio = np.log(e / 610.94)
        Td = 243.04 * ln_ratio / (17.625 - ln_ratio)

    out = pd.Series(Td, index=temp_C.index) > temp_C
    return out.fillna(False)


# %% Original notebook cell 21

def expected_input_columns(cfg: TowerConfig) -> List[str]:
    """Return all sensor columns expected by the QC pipeline."""
    varmaps = [cfg.temp_cols, cfg.rh_cols, cfg.wind_cols, cfg.wdir_cols]
    cols = [col for mapping in varmaps for col in mapping.values()]
    return list(dict.fromkeys(cols))


def preprocess_tower(df: pd.DataFrame, cfg: TowerConfig) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Main QC preprocessing pipeline.

    Returns
    -------
    cleaned : pandas.DataFrame
        Cleaned data with diagnostic and derived columns.
    flags : pandas.DataFrame
        Integer QC bitmask per original variable column.
    summary : pandas.DataFrame
        Summary counts by variable column.
    """
    cleaned = fix_index_and_tz(
        df.copy(),
        tz_local=cfg.timezone,
        naive_are_local=cfg.naive_are_local,
        duplicate_policy=cfg.duplicate_policy,
    )

    inferred_sample_period_s = cfg.sample_period_s or infer_sample_period_s(cleaned.index)

    if cfg.target_freq is not None:
        original_index = cleaned.index.copy()
        cleaned = cleaned.asfreq(cfg.target_freq)
        resample_mask = pd.Series(~cleaned.index.isin(original_index), index=cleaned.index)
    else:
        resample_mask = pd.Series(False, index=cleaned.index)

    cleaned["time_utc"] = cleaned.index.tz_convert("UTC")

    if "dir_wind" in cleaned.columns:
        cleaned["dir_wind"] = pd.to_numeric(cleaned["dir_wind"], errors="coerce") % 360.0

    varmaps = {
        "temp": cfg.temp_cols,
        "rh": cfg.rh_cols,
        "wind": cfg.wind_cols,
        "wdir": cfg.wdir_cols if cfg.wdir_cols else {},
    }

    all_cols = expected_input_columns(cfg)
    missing_cols = [col for col in all_cols if col not in cleaned.columns]
    if missing_cols and cfg.strict_columns:
        raise KeyError(f"Columnas requeridas faltantes para QC: {missing_cols}")
    for col in missing_cols:
        cleaned[col] = np.nan

    for col in all_cols:
        cleaned[col] = pd.to_numeric(cleaned[col], errors="coerce")

    flags = pd.DataFrame(0, index=cleaned.index, columns=all_cols, dtype="int32")
    spike_severity_cols: Dict[str, pd.Series] = {}

    for vtype, mapping in varmaps.items():
        rng = cfg.ranges[vtype]
        step_lim = cfg.step_limits[vtype]
        eps = cfg.persistence_eps[vtype]
        k = cfg.mad_k_by_var[vtype]
        zero_mad_dev = cfg.zero_mad_min_dev[vtype]

        for z, col in mapping.items():
            s = cleaned[col].astype(float)

            missing_fail = s.isna()
            range_fail = apply_range_check(s, rng)
            step_fail = apply_step_check(s, step_lim, vtype, sample_period_s=inferred_sample_period_s)
            persist_fail = apply_persistence_check(s, eps, cfg.persistence_min_samples, vtype)
            spike_fail, spike_severity = apply_spike_mad_check(s, cfg.mad_window, k, vtype, zero_mad_dev)

            set_flag(flags, col, missing_fail, BIT_MISSING)
            set_flag(flags, col, range_fail, BIT_RANGE)
            set_flag(flags, col, step_fail, BIT_STEP)
            set_flag(flags, col, persist_fail, BIT_PERSIST)
            set_flag(flags, col, spike_fail, BIT_SPIKE)

            if vtype == "wind":
                calm_fail = (s < cfg.calm_ws_ms) & s.notna()
                set_flag(flags, col, calm_fail, BIT_CALM)

            inconsist_fail = pd.Series(False, index=cleaned.index)
            if vtype == "rh":
                tcol = cfg.temp_cols.get(z)
                if tcol is not None and tcol in cleaned.columns:
                    inconsist_fail = rh_internal_consistency(cleaned[tcol].astype(float), s)
                    set_flag(flags, col, inconsist_fail, BIT_INCONSIST)

            if cfg.target_freq is not None:
                set_flag(flags, col, resample_mask, BIT_RESAMPLE)

            spike_severity_cols[f"{col}_spike_severity"] = spike_severity

            # Hard-fail policy: RANGE always; STEP and SPIKE only when simultaneous.
            hard_mask = pd.Series(False, index=cleaned.index)
            if BIT_RANGE in cfg.hard_fail_bits:
                hard_mask |= range_fail
            if (BIT_STEP in cfg.hard_fail_bits) and (BIT_SPIKE in cfg.hard_fail_bits):
                hard_mask |= (step_fail & spike_fail)
            elif BIT_STEP in cfg.hard_fail_bits:
                hard_mask |= step_fail
            elif BIT_SPIKE in cfg.hard_fail_bits:
                hard_mask |= spike_fail

            if cfg.remove_persistence and BIT_PERSIST in cfg.hard_fail_bits:
                hard_mask |= persist_fail
            if cfg.remove_rh_inconsistency and BIT_INCONSIST in cfg.hard_fail_bits and vtype == "rh":
                hard_mask |= inconsist_fail

            cleaned.loc[hard_mask, col] = np.nan

    for cname, sev in spike_severity_cols.items():
        cleaned[cname] = sev

    # Thermodynamic derived variables.
    P_site = hypsometric_pressure(cfg.site_altitude_m)
    cleaned["P_Pa"] = float(P_site)

    for z in cfg.heights_m:
        tcol = cfg.temp_cols.get(z)
        rhcol = cfg.rh_cols.get(z)
        if tcol in cleaned.columns and rhcol in cleaned.columns:
            T = cleaned[tcol].astype(float)
            RH = cleaned[rhcol].astype(float)
            RH_for_thermo = RH.clip(0, 100)
            e = (RH_for_thermo / 100.0) * es_tetens_pa(T.to_numpy(dtype=float))
            r = mixing_ratio(np.full(len(T), P_site, dtype=float), e)
            q = specific_humidity_from_r(r)
            theta_v = virtual_potential_temperature(
                T.to_numpy(dtype=float),
                q,
                np.full(len(T), P_site, dtype=float),
            )
            suffix = int(z) if float(z).is_integer() else str(z).replace(".", "p")
            cleaned[f"q_{suffix}"] = q
            cleaned[f"theta_v_{suffix}"] = theta_v

    def count_bits(x: pd.Series, bit: int) -> int:
        vals = x.astype("int64").to_numpy()
        return int(((vals & bit) > 0).sum())

    rows = []
    for col in all_cols:
        if col in cfg.temp_cols.values():
            vtype = "temp"
        elif col in cfg.rh_cols.values():
            vtype = "rh"
        elif col in cfg.wind_cols.values():
            vtype = "wind"
        elif col in cfg.wdir_cols.values():
            vtype = "wdir"
        else:
            vtype = "unknown"

        rows.append({
            "column": col,
            "variable_type": vtype,
            "n": len(flags),
            "missing": count_bits(flags[col], BIT_MISSING),
            "range": count_bits(flags[col], BIT_RANGE),
            "step": count_bits(flags[col], BIT_STEP),
            "persistence": count_bits(flags[col], BIT_PERSIST),
            "spike": count_bits(flags[col], BIT_SPIKE),
            "calm": count_bits(flags[col], BIT_CALM) if vtype == "wind" else 0,
            "inconsistency": count_bits(flags[col], BIT_INCONSIST) if vtype == "rh" else 0,
            "resample": count_bits(flags[col], BIT_RESAMPLE),
            "sample_period_s": inferred_sample_period_s,
            "mad_k_used": cfg.mad_k_by_var.get(vtype, np.nan),
            "hard_fail_policy": "RANGE or STEP&SPIKE; optional PERSIST/INCONSIST controlled by config",
            "removed_count": int(cleaned[col].isna().sum()),
        })

    summary = pd.DataFrame(rows).set_index("column")

    for path, obj in [
        (cfg.save_clean_csv, cleaned),
        (cfg.save_flags_csv, flags),
        (cfg.save_summary_csv, summary),
    ]:
        if path:
            ensure_parent_dir(path)
            obj.to_csv(path)

    for path, obj in [
        (cfg.save_clean_parquet, cleaned),
        (cfg.save_flags_parquet, flags),
        (cfg.save_summary_parquet, summary),
    ]:
        if path:
            ensure_parent_dir(path)
            obj.to_parquet(path)

    return cleaned, flags, summary


# %% Original notebook cell 23

def audit_dataframe_integrity(df: pd.DataFrame, name: str = "DataFrame") -> pd.DataFrame:
    """Return a compact integrity audit for a DataFrame."""
    rows = []
    rows.append({"item": "name", "value": name})
    rows.append({"item": "n_rows", "value": len(df)})
    rows.append({"item": "n_columns", "value": len(df.columns)})
    rows.append({"item": "index_type", "value": type(df.index).__name__})
    rows.append({"item": "is_datetime_index", "value": isinstance(df.index, pd.DatetimeIndex)})
    if isinstance(df.index, pd.DatetimeIndex):
        rows.append({"item": "timezone", "value": str(df.index.tz)})
        rows.append({"item": "time_min", "value": str(df.index.min())})
        rows.append({"item": "time_max", "value": str(df.index.max())})
        rows.append({"item": "duplicated_timestamps", "value": int(df.index.duplicated().sum())})
        rows.append({"item": "is_monotonic_increasing", "value": bool(df.index.is_monotonic_increasing)})
        rows.append({"item": "inferred_sample_period_s", "value": infer_sample_period_s(df.index)})
    rows.append({"item": "total_nan", "value": int(df.isna().sum().sum())})
    return pd.DataFrame(rows)


def check_required_columns(df: pd.DataFrame, cols: Sequence[str], label: str = "DataFrame") -> None:
    """Raise an error if required columns are missing."""
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise KeyError(f"{label} no contiene las columnas requeridas: {missing}")
    print(f"{label}: todas las columnas requeridas están presentes ({len(cols)} columnas).")


# %% Original notebook cell 25

def dataframe_to_stacked_da(
    df: pd.DataFrame,
    name: str,
    heights_m: Sequence[float],
    col_map: Dict[float, str],
    units: str,
    long_name: str,
    time_coord: xr.DataArray,
    standard_name: Optional[str] = None,
) -> Optional[xr.DataArray]:
    """Convert selected DataFrame columns into a 2-D DataArray(time, height)."""
    xarray = require_xarray()
    if df is None:
        return None
    if not isinstance(df, pd.DataFrame):
        raise TypeError(f"df for {name} must be a pandas DataFrame.")

    das = []
    for z in sorted([z for z in heights_m if z in col_map]):
        col_name = col_map[z]
        if col_name in df.columns:
            values = pd.to_numeric(df[col_name], errors="coerce").to_numpy()
            if len(values) != len(time_coord):
                raise ValueError(
                    f"Longitud incompatible para {name}/{col_name}: {len(values)} vs {len(time_coord)}"
                )
            da = xarray.DataArray(values, dims=("time",), coords={"time": time_coord}).expand_dims(height=[z])
            das.append(da)

    if not das:
        return None

    stacked = xarray.concat(das, dim="height").sortby("height")
    stacked.name = name
    stacked.attrs = {"units": units, "long_name": long_name}
    if standard_name:
        stacked.attrs["standard_name"] = standard_name
    return stacked


def add_derived_thermo_variables(
    ds_root: xr.Dataset,
    cleaned_df: pd.DataFrame,
    heights_m: Sequence[float],
    time_coord: xr.DataArray,
) -> None:
    """Add q(time,height), theta_v(time,height) and P_Pa(time) to a Dataset."""
    xarray = require_xarray()
    for var_prefix, units, long_name, standard_name in [
        ("q", "kg kg-1", "Specific Humidity", "specific_humidity"),
        ("theta_v", "K", "Virtual Potential Temperature", "virtual_potential_temperature"),
    ]:
        das = []
        for z in sorted(heights_m):
            suffix = int(z) if float(z).is_integer() else str(z).replace(".", "p")
            col_name = f"{var_prefix}_{suffix}"
            if col_name in cleaned_df.columns:
                vals = pd.to_numeric(cleaned_df[col_name], errors="coerce").to_numpy()
                if len(vals) != len(time_coord):
                    raise ValueError(f"Longitud incompatible para {col_name}.")
                da = xarray.DataArray(vals, dims=("time",), coords={"time": time_coord}).expand_dims(height=[z])
                das.append(da)
        if das:
            ds_root[var_prefix] = xarray.concat(das, dim="height").sortby("height")
            ds_root[var_prefix].attrs = {
                "units": units,
                "long_name": long_name,
                "standard_name": standard_name,
            }

    if "P_Pa" in cleaned_df.columns:
        vals = pd.to_numeric(cleaned_df["P_Pa"], errors="coerce").to_numpy()
        if len(vals) != len(time_coord):
            raise ValueError("Longitud incompatible para P_Pa.")
        ds_root["P_Pa"] = xarray.DataArray(vals, dims=("time",), coords={"time": time_coord})
        ds_root["P_Pa"].attrs = {
            "units": "Pa",
            "long_name": "Atmospheric Pressure at Site Elevation",
            "standard_name": "air_pressure",
            "description": "Pressure estimated from site altitude using a standard-atmosphere hypsometric relation.",
        }


def save_tower_data_to_netcdf(
    cleaned_df: pd.DataFrame,
    flags_df: pd.DataFrame,
    config: TowerConfig,
    output_filename: str | Path,
    raw_df: Optional[pd.DataFrame] = None,
    global_attrs: Optional[Dict[str, object]] = None,
) -> None:
    """Export cleaned data, QC flags and optional raw data to NetCDF4."""
    xarray = require_xarray()
    output_filename = Path(output_filename)
    ensure_parent_dir(output_filename)

    if not isinstance(cleaned_df.index, pd.DatetimeIndex):
        raise ValueError("cleaned_df must have a DatetimeIndex.")

    if cleaned_df.index.tz is not None:
        standard_time = cleaned_df.index.tz_convert("UTC").tz_localize(None)
    else:
        standard_time = cleaned_df.index

    time_coord = xarray.DataArray(
        standard_time,
        dims=("time",),
        name="time",
        attrs={"standard_name": "time", "axis": "T", "long_name": "Time (UTC)"},
    )
    height_coord = xarray.DataArray(
        np.sort(config.heights_m),
        dims=("height",),
        name="height",
        attrs={"units": "m", "standard_name": "height", "axis": "Z", "positive": "up"},
    )

    ds_main = xarray.Dataset(coords={"time": time_coord, "height": height_coord})

    for var, units, long, col_map, std in [
        ("ta", "degree_C", "Air Temperature", config.temp_cols, "air_temperature"),
        ("hur", "%", "Relative Humidity", config.rh_cols, "relative_humidity"),
        ("ws", "m s-1", "Wind Speed", config.wind_cols, "wind_speed"),
        ("wd", "degree", "Wind Direction", config.wdir_cols, "wind_from_direction"),
    ]:
        da = dataframe_to_stacked_da(cleaned_df, var, config.heights_m, col_map, units, long, time_coord, std)
        if da is not None:
            ds_main[var] = da

    add_derived_thermo_variables(ds_main, cleaned_df, config.heights_m, time_coord)

    for fvar, col_map, long in [
        ("ta_qc_flags", config.temp_cols, "QC Flags for Temperature"),
        ("hur_qc_flags", config.rh_cols, "QC Flags for Relative Humidity"),
        ("ws_qc_flags", config.wind_cols, "QC Flags for Wind Speed"),
        ("wd_qc_flags", config.wdir_cols, "QC Flags for Wind Direction"),
    ]:
        fda = dataframe_to_stacked_da(flags_df, fvar, config.heights_m, col_map, "1", long, time_coord)
        if fda is not None:
            ds_main[fvar] = fda.fillna(BIT_MISSING).astype(np.int32)

    for var in [v for v in ds_main.data_vars if v.endswith("_qc_flags")]:
        ds_main[var].attrs.update({
            "flag_masks": FLAG_MASKS_CF,
            "flag_meanings": FLAG_MEANINGS_CF,
            "comment": FLAG_COMMENT_CF,
        })

    ds_main.attrs.update({
        "title": "Cleaned Meteorological Tower Data - OGHYO Project",
        "institution": "Instituto Geofísico del Perú (IGP)",
        "project": "ACNS - Andean Convective Nowcasting System",
        "history": f"Created {datetime.utcnow().isoformat()}Z",
        "Conventions": "CF-1.8",
        "site_altitude_m": float(config.site_altitude_m),
        "timezone_original": config.timezone,
        "pressure_source": "estimated_from_site_altitude_using_standard_atmosphere",
    })
    if global_attrs:
        ds_main.attrs.update(global_attrs)

    encoding = {var: {"zlib": True, "complevel": 4} for var in ds_main.data_vars}
    encoding["time"] = {
        "units": "seconds since 1970-01-01 00:00:00",
        "calendar": "proleptic_gregorian",
        "dtype": "int64",
    }

    ds_main.to_netcdf(
        output_filename,
        format="NETCDF4",
        engine="netcdf4",
        mode="w",
        encoding=encoding,
    )

    if raw_df is not None:
        raw_fixed = raw_df.copy()
        if isinstance(raw_fixed.index, pd.DatetimeIndex):
            if raw_fixed.index.tz is not None:
                raw_fixed.index = raw_fixed.index.tz_convert("UTC").tz_localize(None)
        raw_fixed = raw_fixed.reindex(pd.DatetimeIndex(standard_time))

        ds_raw = xarray.Dataset(coords={"time": time_coord})
        for col in raw_fixed.columns:
            vals = pd.to_numeric(raw_fixed[col], errors="coerce").to_numpy()
            if np.isfinite(vals).sum() > 0:
                safe_col = str(col).replace(" ", "_").replace("/", "_")
                ds_raw[safe_col] = xarray.DataArray(vals, dims=("time",), coords={"time": time_coord})
                ds_raw[safe_col].attrs["original_column_name"] = str(col)
        ds_raw.attrs = {
            "title": "Original Uncontrolled Data",
            "description": "Original raw numeric variables reindexed to the same UTC time axis used by cleaned dataset.",
        }
        ds_raw.to_netcdf(
            output_filename,
            group="raw_uncontrolled",
            engine="netcdf4",
            mode="a",
            encoding={"time": encoding["time"]},
        )

    print(f"NetCDF exportado correctamente: {output_filename}")


# %% Original notebook cell 27

def run_full_qc_pipeline(
    temp_calib_file: str | Path = TEMP_CALIB_FILE,
    rh_calib_file: str | Path = RH_CALIB_FILE,
    tower_mat_file: str | Path = TOWER_MAT_FILE,
    sun_mat_file: str | Path = SUN_MAT_FILE,
    output_netcdf: str | Path = OUTPUT_NETCDF,
    cfg: Optional[TowerConfig] = None,
    export_netcdf: bool = True,
    global_attrs: Optional[Dict[str, object]] = None,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Run the complete optimized QC workflow.

    Returns
    -------
    raw_prepared : pandas.DataFrame
        Calibrated and time-indexed input data before QC.
    cleaned : pandas.DataFrame
        Cleaned data with derived variables.
    flags : pandas.DataFrame
        Bitmask QC flags.
    summary : pandas.DataFrame
        QC summary by variable.
    missing_summary : pandas.DataFrame
        NaN summary before QC.
    """
    if cfg is None:
        cfg = TowerConfig(strict_columns=STRICT_COLUMNS)

    temp_param = read_calibration_matrix(temp_calib_file, n_sensors=6)
    rh_param = read_calibration_matrix(rh_calib_file, n_sensors=6)
    temp_cal = calibration_dict(temp_param, prefix="temp_n", n_sensors=6)
    rh_cal = calibration_dict(rh_param, prefix="RH_n", n_sensors=6)

    tower_mat = load_mat_file(tower_mat_file)
    sun_mat = load_mat_file(sun_mat_file)

    raw_df = build_tower_dataframe_from_mat(tower_mat, sun_mat, temp_cal, rh_cal)
    raw_prepared = add_datetime_and_sunrise(
        raw_df,
        timezone=cfg.timezone,
        site_name=SITE_NAME,
        site_region=SITE_REGION,
        latitude=SITE_LAT,
        longitude=SITE_LON,
        duplicate_policy=cfg.duplicate_policy,
    )

    missing_summary = summarize_missing_values(raw_prepared)
    cleaned, flags, summary = preprocess_tower(raw_prepared, cfg)

    if export_netcdf:
        if global_attrs is None:
            global_attrs = {
                "title": "Surface Boundary Layer Observations - Mantaro Valley",
                "institution": "Instituto Geofísico del Perú (IGP)",
                "references": "https://doi.org/10.1016/j.agrformet.2025.110570",
                "creator_name": "Dr. José Luis Flores Rojas",
                "comment": "1-minute averaged data from the ACNS project tower.",
                "description": "Full dataset including raw uncontrolled values, cleaned values and QC bitmask flags.",
            }
        save_tower_data_to_netcdf(
            cleaned_df=cleaned,
            flags_df=flags,
            config=cfg,
            output_filename=output_netcdf,
            raw_df=raw_prepared,
            global_attrs=global_attrs,
        )

    return raw_prepared, cleaned, flags, summary, missing_summary

def make_default_qc_config() -> TowerConfig:
    """Return the audited QC configuration without executing the pipeline."""
    return TowerConfig(
        heights_m=[2.0, 6.0, 12.0, 24.0],
        temp_cols={2.0: "temp_n1", 6.0: "temp_n2", 12.0: "temp_n3", 24.0: "temp_n5"},
        rh_cols={2.0: "RH_n1", 6.0: "RH_n2", 12.0: "RH_n3", 24.0: "RH_n5"},
        wind_cols={2.0: "wind_n1", 6.0: "wind_n2", 12.0: "wind_n3", 24.0: "wind_n5"},
        wdir_cols={24.0: "dir_wind"},
        site_altitude_m=3315.0,
        timezone="America/Lima",
        naive_are_local=True,
        duplicate_policy="first",
        target_freq="1min",
        strict_columns=STRICT_COLUMNS,
        ranges={"temp": (-20.0, 40.0), "rh": (0.0, 100.0), "wind": (0.0, 50.0), "wdir": (0.0, 360.0)},
        step_limits={"temp": 1.5, "rh": 8.0, "wind": 10.0, "wdir": 120.0},
        persistence_eps={"temp": 0.1, "rh": 0.2, "wind": 0.05, "wdir": 2.0},
        persistence_min_samples=20,
        mad_window=21,
        mad_k_by_var={"temp": 5.0, "rh": 6.0, "wind": 10.0, "wdir": 10.0},
        zero_mad_min_dev={"temp": 0.2, "rh": 1.0, "wind": 0.2, "wdir": 5.0},
        calm_ws_ms=0.2,
        hard_fail_bits=(BIT_RANGE, BIT_STEP, BIT_SPIKE),
        remove_persistence=False,
        remove_rh_inconsistency=False,
    )

